// tools/lingxia-cli/templates/lxapp-create/pages/home/index.vue
<script setup lang="ts">
import '../../app.css';
import { LxNavigator, useLxPage } from '@lingxia/vue';
import { computed, ref } from 'vue';

type PageState = { greeting?: string };
type PageActions = { greet(payload: { name: string }): void };

const { data, actions } = useLxPage<PageState, PageActions>();
const greeting = computed(() => data?.greeting ?? '');
const inputName = ref('');

function handleSubmit() {
  const name = inputName.value.trim();
  if (name) actions.greet({ name });
}
</script>

<template>
  <main class="page">
    <section class="card">
      <h1>Hello, LingXia</h1>
      <div class="form">
        <input
          v-model="inputName"
          class="input"
          data-testid="home-name"
          placeholder="Enter your name"
          @keydown.enter.prevent="handleSubmit"
        />
        <button class="btn" data-testid="home-greet" :disabled="!inputName.trim()" @click="handleSubmit">Say Hello</button>
      </div>
      <p v-if="greeting" class="greeting" data-testid="home-greeting">{{ greeting }}</p>
      <LxNavigator url="https://www.lingxia.app" class="link">lingxia.app →</LxNavigator>
    </section>
  </main>
</template>

// tools/lingxia-cli/templates/lxapp-create/pages/home/index.tsx
import React from 'react';
import { LxNavigator, useLxPage } from '@lingxia/react';
import '../../app.css';

type PageState = { greeting: string };
type PageActions = { greet(payload: { name: string }): void };

export default function HomePage() {
  const { data, actions } = useLxPage<PageState, PageActions>();
  const [name, setName] = React.useState('');
  const submit = () => name.trim() && actions.greet({ name: name.trim() });

  return (
    <main className="page">
      <section className="card">
        <h1>Hello, LingXia</h1>
        <div className="form">
          <input
            className="input"
            data-testid="home-name"
            value={name}
            placeholder="Enter your name"
            onChange={e => setName(e.target.value)}
            onKeyDown={e => e.key === 'Enter' && submit()}
          />
          <button className="btn" data-testid="home-greet" onClick={submit} disabled={!name.trim()}>
            Say Hello
          </button>
        </div>
        {data.greeting && <p className="greeting" data-testid="home-greeting">{data.greeting}</p>}
        <LxNavigator url="https://www.lingxia.app" className="link">
          lingxia.app →
        </LxNavigator>
      </section>
    </main>
  );
}
