// examples/lingxia-showcase/lxapp/pages/surface/index.tsx
import React from 'react';
import { useLxPage } from '@lingxia/react';
import '../../tailwind.css';

export default function SurfacePage() {
  const { data, actions } = useLxPage();
  const { logSurfaceMessage, hideSelf, closeSelf } = actions;
  const queryString = data.queryString ?? '';
  const showCount = data.showCount ?? 0;
  const hideCount = data.hideCount ?? 0;
  const lastLifecycle = data.lastLifecycle ?? 'onLoad';
  const inboundCount = data.inboundCount ?? 0;
  const lastInbound = data.lastInbound ?? '';
  const [message, setMessage] = React.useState('');
  // The counter survives hide() → show() round-trips because the page mount
  // is preserved. After close() the page is destroyed and the counter resets,
  // which is the visible difference between hide and close.
  const [counter, setCounter] = React.useState(0);

  const handleSend = React.useCallback(async () => {
    const text = message.trim();
    if (!text) {
      return;
    }

    try {
      await logSurfaceMessage({ message: text });
      setMessage('');
    } catch (error) {
      console.error('logSurfaceMessage failed:', error);
    }
  }, [message, logSurfaceMessage]);

  return (
    <div
      data-testid="surface-page"
      className="min-h-screen bg-surface-100 text-gray-900 flex flex-col items-center px-4 py-6"
    >
      <div className="w-full max-w-md space-y-6">
        <header>
          <h1 className="text-lg font-semibold tracking-wide text-gray-900">Surface Page</h1>
          <p className="text-sm text-gray-500 mt-1">
            Inspect the query string and send a message to the opener.
          </p>
        </header>

        <section className="bg-surface rounded-xl border border-line-200 p-4 space-y-2 shadow-sm">
          <div className="text-xs uppercase text-gray-500 tracking-wide">Query String</div>
          <div className="font-mono text-sm text-gray-800 break-words">
            {queryString || '(none)'}
          </div>
        </section>

        <section className="bg-surface rounded-xl border border-line-200 p-4 space-y-3 shadow-sm">
          <div className="text-xs uppercase text-gray-500 tracking-wide">Page lifecycle</div>
          <div className="grid grid-cols-2 gap-2 text-sm">
            <div className="bg-surface-50 rounded-md px-3 py-2">
              <div className="text-xs text-gray-500">onShow</div>
              <div data-testid="surface-show-count" className="font-mono text-base text-gray-900">
                {showCount}
              </div>
            </div>
            <div className="bg-surface-50 rounded-md px-3 py-2">
              <div className="text-xs text-gray-500">onHide</div>
              <div className="font-mono text-base text-gray-900">{hideCount}</div>
            </div>
          </div>
          <div className="text-xs text-gray-500">
            Last event: <span className="font-mono text-gray-800">{lastLifecycle}</span>
          </div>
        </section>

        <section className="bg-surface rounded-xl border border-line-200 p-4 space-y-3 shadow-sm">
          <div className="text-xs uppercase text-gray-500 tracking-wide">In-page counter</div>
          <div className="font-mono text-2xl text-gray-900">{counter}</div>
          <div className="text-xs text-gray-500">
            Hide preserves this counter; close resets it on re-open.
          </div>
          <button
            type="button"
            onClick={() => setCounter((value) => value + 1)}
            className="w-full h-10 text-sm font-medium rounded-md bg-surface-200 hover:bg-surface-300 text-gray-900 transition-colors"
          >
            Increment
          </button>
        </section>

        <section className="bg-surface rounded-xl border border-line-200 p-4 space-y-2 shadow-sm">
          <div className="text-xs uppercase text-gray-500 tracking-wide">From opener</div>
          <div className="text-xs text-gray-500">
            Received: <span data-testid="surface-inbound-count" className="font-mono text-gray-800">{inboundCount}</span>
          </div>
          <div data-testid="surface-inbound" className="font-mono text-sm text-gray-800 break-words">
            {lastInbound || '(none)'}
          </div>
        </section>

        <section className="bg-surface rounded-xl border border-line-200 p-4 space-y-3 shadow-sm">
          <div className="text-xs uppercase text-gray-500 tracking-wide">Message</div>
          <input
            className="w-full px-3 py-2 rounded-md bg-surface border border-line-300 text-sm text-gray-900 focus:outline-hidden focus:ring-2 focus:ring-blue-500"
            placeholder="Message to parent page"
            data-controlled-value={message}
            value={message}
            onChange={(event) => setMessage(event.target.value)}
          />
          <button
            type="button"
            data-testid="surface-send-message"
            onClick={handleSend}
            className="w-full h-10 text-sm font-medium rounded-md bg-blue-500 hover:bg-blue-600 text-white transition-colors"
          >
            Send then close
          </button>
        </section>

        <section className="bg-surface rounded-xl border border-line-200 p-4 space-y-3 shadow-sm">
          <div className="text-xs uppercase text-gray-500 tracking-wide">Self actions</div>
          <button
            type="button"
            onClick={() => hideSelf?.()}
            className="w-full h-10 text-sm font-medium rounded-md bg-amber-500 hover:bg-amber-600 text-white transition-colors"
          >
            Hide (parent can show again)
          </button>
          <button
            type="button"
            onClick={() => closeSelf?.()}
            className="w-full h-10 text-sm font-medium rounded-md bg-rose-500 hover:bg-rose-600 text-white transition-colors"
          >
            Close (destroys this page)
          </button>
        </section>
      </div>
    </div>
  );
}

// examples/lingxia-showcase/lxapp/pages/surface/index.vue
<template>
  <div
    data-testid="surface-page"
    class="min-h-screen bg-surface-100 text-gray-900 flex flex-col items-center px-4 py-6"
  >
    <div class="w-full max-w-md space-y-6">
      <header>
        <h1 class="text-lg font-semibold tracking-wide text-gray-900">Surface Page</h1>
        <p class="text-sm text-gray-500 mt-1">
          Inspect the query string, send messages, and toggle hide / close.
        </p>
      </header>

      <section class="bg-surface rounded-xl border border-line-200 p-4 space-y-2 shadow-sm">
        <div class="text-xs uppercase text-gray-500 tracking-wide">Query String</div>
        <div class="font-mono text-sm text-gray-800 break-words">
          {{ queryString || '(none)' }}
        </div>
      </section>

      <section class="bg-surface rounded-xl border border-line-200 p-4 space-y-3 shadow-sm">
        <div class="text-xs uppercase text-gray-500 tracking-wide">Page lifecycle</div>
        <div class="grid grid-cols-2 gap-2 text-sm">
          <div class="bg-surface-50 rounded-md px-3 py-2">
            <div class="text-xs text-gray-500">onShow</div>
            <div data-testid="surface-show-count" class="font-mono text-base text-gray-900">
              {{ showCount }}
            </div>
          </div>
          <div class="bg-surface-50 rounded-md px-3 py-2">
            <div class="text-xs text-gray-500">onHide</div>
            <div class="font-mono text-base text-gray-900">{{ hideCount }}</div>
          </div>
        </div>
        <div class="text-xs text-gray-500">
          Last event: <span class="font-mono text-gray-800">{{ lastLifecycle }}</span>
        </div>
      </section>

      <section class="bg-surface rounded-xl border border-line-200 p-4 space-y-3 shadow-sm">
        <div class="text-xs uppercase text-gray-500 tracking-wide">In-page counter</div>
        <div class="font-mono text-2xl text-gray-900">{{ counter }}</div>
        <div class="text-xs text-gray-500">
          Hide preserves this counter; close resets it on re-open.
        </div>
        <button type="button" @click="counter++"
          class="w-full h-10 text-sm font-medium rounded-md bg-surface-200 hover:bg-surface-300 text-gray-900 transition-colors">
          Increment
        </button>
      </section>

      <section class="bg-surface rounded-xl border border-line-200 p-4 space-y-2 shadow-sm">
        <div class="text-xs uppercase text-gray-500 tracking-wide">From opener</div>
        <div class="text-xs text-gray-500">
          Received: <span data-testid="surface-inbound-count" class="font-mono text-gray-800">{{ inboundCount }}</span>
        </div>
        <div data-testid="surface-inbound" class="font-mono text-sm text-gray-800 break-words">
          {{ lastInbound || '(none)' }}
        </div>
      </section>

      <section class="bg-surface rounded-xl border border-line-200 p-4 space-y-3 shadow-sm">
        <div class="text-xs uppercase text-gray-500 tracking-wide">Message</div>
        <input
          class="w-full px-3 py-2 rounded-md bg-surface border border-line-300 text-sm text-gray-900 focus:outline-hidden focus:ring-2 focus:ring-blue-500"
          placeholder="Message to parent page"
          v-model="message"
          :data-controlled-value="message"
        />
        <button
          type="button"
          data-testid="surface-send-message"
          @click="handleSend"
          class="w-full h-10 text-sm font-medium rounded-md bg-blue-500 hover:bg-blue-600 text-white transition-colors"
        >
          Send then close
        </button>
      </section>

      <section class="bg-surface rounded-xl border border-line-200 p-4 space-y-3 shadow-sm">
        <div class="text-xs uppercase text-gray-500 tracking-wide">Self actions</div>
        <button type="button" @click="hideSelf?.()"
          class="w-full h-10 text-sm font-medium rounded-md bg-amber-500 hover:bg-amber-600 text-white transition-colors">
          Hide (parent can show again)
        </button>
        <button type="button" @click="closeSelf?.()"
          class="w-full h-10 text-sm font-medium rounded-md bg-rose-500 hover:bg-rose-600 text-white transition-colors">
          Close (destroys this page)
        </button>
      </section>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import { useLxPage } from '@lingxia/vue';
import '../../tailwind.css';

const { data, actions } = useLxPage();
const { logSurfaceMessage, hideSelf, closeSelf } = actions;

const message = ref('');
// Counter survives hide() → show() (page mount stays alive) but resets on close().
const counter = ref(0);

const queryString = computed(() => data.queryString ?? '');
const showCount = computed(() => data.showCount ?? 0);
const hideCount = computed(() => data.hideCount ?? 0);
const lastLifecycle = computed(() => data.lastLifecycle ?? 'onLoad');
const inboundCount = computed(() => data.inboundCount ?? 0);
const lastInbound = computed(() => data.lastInbound ?? '');

async function handleSend() {
  const text = message.value.trim();
  if (!text) return;

  try {
    await logSurfaceMessage({ message: text });
    message.value = '';
  } catch (error) {
    console.error('logSurfaceMessage failed:', error);
  }
}
</script>
