// lingxia-components/src/vue/LxInput.vue
<script setup lang="ts">
import { computed, h, onBeforeUnmount, ref, useAttrs, watch } from 'vue';
import { registerInputComponent } from '../input.js';
import type { LxInputProps } from './types.js';
import {
  appendBindingAndDatasetAttrs,
  bindElementEvents,
  getCustomEventDetail,
  unbindElementEvents,
} from './text_component_shared.js';

const props = withDefaults(defineProps<LxInputProps>(), {
  type: 'text',
  disabled: false,
  confirmType: 'done',
});
const attrs = useAttrs();

const emit = defineEmits<{
  'update:modelValue': [value: string];
  input: [detail: Record<string, unknown>];
  change: [detail: Record<string, unknown>];
  focus: [detail: Record<string, unknown>];
  blur: [detail: Record<string, unknown>];
  confirm: [detail: Record<string, unknown>];
  keyboardHeightChange: [detail: Record<string, unknown>];
  nicknameReview: [detail: Record<string, unknown>];
}>();

if (typeof window !== 'undefined') {
  registerInputComponent();
}

const elementRef = ref<HTMLElement | null>(null);
let boundElement: HTMLElement | null = null;

const inputEventListeners: Record<string, EventListenerObject> = {
  input: {
    handleEvent: (event: Event) => {
      const detail = getCustomEventDetail<Record<string, unknown>>(event);
      if (typeof detail.value === 'string') {
        emit('update:modelValue', detail.value);
      }
      emit('input', detail);
    },
  },
  change: {
    handleEvent: (event: Event) => emit('change', getCustomEventDetail<Record<string, unknown>>(event)),
  },
  focus: {
    handleEvent: (event: Event) => emit('focus', getCustomEventDetail<Record<string, unknown>>(event)),
  },
  blur: {
    handleEvent: (event: Event) => emit('blur', getCustomEventDetail<Record<string, unknown>>(event)),
  },
  confirm: {
    handleEvent: (event: Event) => emit('confirm', getCustomEventDetail<Record<string, unknown>>(event)),
  },
  keyboardheightchange: {
    handleEvent: (event: Event) => emit('keyboardHeightChange', getCustomEventDetail<Record<string, unknown>>(event)),
  },
  nicknamereview: {
    handleEvent: (event: Event) => emit('nicknameReview', getCustomEventDetail<Record<string, unknown>>(event)),
  },
};

watch(elementRef, (element) => {
  boundElement = bindElementEvents(boundElement, element, inputEventListeners);
});

onBeforeUnmount(() => {
  unbindElementEvents(boundElement, inputEventListeners);
});

const inputProps = computed<Record<string, unknown>>(() => {
  const result: Record<string, unknown> = {};
  const explicitId =
    typeof props.id === 'string'
      ? props.id.trim()
      : typeof attrs.id === 'string'
        ? attrs.id.trim()
        : '';

  if (explicitId.length > 0) result.id = explicitId;

  if (props.modelValue !== undefined) {
    result.value = props.modelValue;
  } else if (props.value !== undefined) {
    result.value = props.value;
  } else if (!elementRef.value && props.defaultValue !== undefined) {
    result.value = props.defaultValue;
  }

  if (props.type) result.type = props.type;
  if (props.password) result.password = 'true';
  if (props.placeholder) result.placeholder = props.placeholder;
  if (props.placeholderStyle) result['placeholder-style'] = props.placeholderStyle;
  if (props.placeholderClass) result['placeholder-class'] = props.placeholderClass;
  if (props.maxlength !== undefined) result.maxlength = String(props.maxlength);
  if (props.cursorSpacing !== undefined) result['cursor-spacing'] = String(props.cursorSpacing);
  if (props.autoFocus) result['auto-focus'] = 'true';
  if (props.disabled) result.disabled = 'true';
  if (props.focus !== undefined) result.focus = props.focus ? 'true' : 'false';
  if (props.confirmType) result['confirm-type'] = props.confirmType;
  if (props.alwaysEmbed) result['always-embed'] = 'true';
  if (props.confirmHold) result['confirm-hold'] = 'true';
  if (props.cursor !== undefined) result.cursor = String(props.cursor);
  if (props.cursorColor) result['cursor-color'] = props.cursorColor;
  if (props.selectionStart !== undefined) result['selection-start'] = String(props.selectionStart);
  if (props.selectionEnd !== undefined) result['selection-end'] = String(props.selectionEnd);
  if (props.adjustPosition === false) result['adjust-position'] = 'false';
  if (props.holdKeyboard) result['hold-keyboard'] = 'true';

  if (props.bindInput) result.bindinput = props.bindInput;
  if (props.bindChange) result.bindchange = props.bindChange;
  if (props.bindFocus) result.bindfocus = props.bindFocus;
  if (props.bindBlur) result.bindblur = props.bindBlur;
  if (props.bindConfirm) result.bindconfirm = props.bindConfirm;
  if (props.bindKeyboardHeightChange) result.bindkeyboardheightchange = props.bindKeyboardHeightChange;
  if (props.bindNicknameReview) result.bindnicknamereview = props.bindNicknameReview;
  if (props.catchInput) result.catchinput = props.catchInput;
  if (props.catchChange) result.catchchange = props.catchChange;
  if (props.catchFocus) result.catchfocus = props.catchFocus;
  if (props.catchBlur) result.catchblur = props.catchBlur;
  if (props.catchConfirm) result.catchconfirm = props.catchConfirm;
  if (props.catchKeyboardHeightChange) result.catchkeyboardheightchange = props.catchKeyboardHeightChange;
  if (props.catchNicknameReview) result.catchnicknamereview = props.catchNicknameReview;

  appendBindingAndDatasetAttrs(attrs as Record<string, unknown>, result as Record<string, string>);

  result.class = props.class ?? attrs.class;
  result.style = props.style ?? attrs.style;
  return result;
});

defineExpose({ el: elementRef });

const renderInput = () => h('lx-input', { ref: elementRef, ...inputProps.value });
</script>

<template>
  <renderInput />
</template>

// lingxia-components/src/react/LxInput.tsx
import React, { forwardRef, useCallback, useEffect, useRef } from "react";
import { registerInputComponent } from "../input.js";
import {
  appendBindingAndDatasetAttrs,
  bindEventListeners,
  getCustomEventDetail,
  unbindEventListeners,
} from "./text_component_shared.js";

export interface LxInputEventDetail {
  value?: string;
  cursor?: number;
  keyCode?: number;
  height?: number;
  duration?: number;
  encryptedValue?: string;
  encryptError?: string;
  pass?: boolean;
  timeout?: boolean;
}

export interface LxInputProps {
  id?: string;
  value?: string;
  defaultValue?: string;
  type?: "text" | "number" | "password" | "digit";
  password?: boolean;
  placeholder?: string;
  placeholderStyle?: string;
  placeholderClass?: string;
  maxlength?: number;
  cursorSpacing?: number;
  autoFocus?: boolean;
  disabled?: boolean;
  focus?: boolean;
  confirmType?: "send" | "search" | "next" | "go" | "done";
  alwaysEmbed?: boolean;
  confirmHold?: boolean;
  cursor?: number;
  cursorColor?: string;
  selectionStart?: number;
  selectionEnd?: number;
  adjustPosition?: boolean;
  holdKeyboard?: boolean;

  onInput?: (detail: LxInputEventDetail) => void;
  onChange?: (detail: LxInputEventDetail) => void;
  onFocus?: (detail: LxInputEventDetail) => void;
  onBlur?: (detail: LxInputEventDetail) => void;
  onConfirm?: (detail: LxInputEventDetail) => void;
  onKeyboardHeightChange?: (detail: LxInputEventDetail) => void;
  onNicknameReview?: (detail: LxInputEventDetail) => void;

  bindInput?: string;
  bindChange?: string;
  bindFocus?: string;
  bindBlur?: string;
  bindConfirm?: string;
  bindKeyboardHeightChange?: string;
  bindNicknameReview?: string;
  catchInput?: string;
  catchChange?: string;
  catchFocus?: string;
  catchBlur?: string;
  catchConfirm?: string;
  catchKeyboardHeightChange?: string;
  catchNicknameReview?: string;

  className?: string;
  style?: React.CSSProperties;
}

if (typeof window !== "undefined") {
  registerInputComponent();
}

export const LxInput = forwardRef<HTMLElement, LxInputProps>(({
  value,
  defaultValue,
  type,
  password,
  placeholder,
  placeholderStyle,
  placeholderClass,
  maxlength,
  cursorSpacing,
  autoFocus,
  disabled,
  focus,
  confirmType,
  alwaysEmbed,
  confirmHold,
  cursor,
  cursorColor,
  selectionStart,
  selectionEnd,
  adjustPosition,
  holdKeyboard,
  onInput,
  onChange,
  onFocus,
  onBlur,
  onConfirm,
  onKeyboardHeightChange,
  onNicknameReview,
  bindInput,
  bindChange,
  bindFocus,
  bindBlur,
  bindConfirm,
  bindKeyboardHeightChange,
  bindNicknameReview,
  catchInput,
  catchChange,
  catchFocus,
  catchBlur,
  catchConfirm,
  catchKeyboardHeightChange,
  catchNicknameReview,
  className,
  style,
  id,
  ...rest
}, ref) => {
  const hasMountedRef = useRef(false);
  const initialValueRef = useRef(defaultValue);
  const didInitialNativeSyncRef = useRef(false);

  const propsRef = useRef({
    onInput,
    onChange,
    onFocus,
    onBlur,
    onConfirm,
    onKeyboardHeightChange,
    onNicknameReview,
  });
  propsRef.current = {
    onInput,
    onChange,
    onFocus,
    onBlur,
    onConfirm,
    onKeyboardHeightChange,
    onNicknameReview,
  };

  const boundRef = useRef<HTMLElement | null>(null);
  const boundListenersRef = useRef<Record<string, EventListenerObject> | null>(null);

  const inputRefCallback = useCallback((el: HTMLElement | null) => {
    if (typeof ref === "function") ref(el);
    else if (ref) (ref as React.MutableRefObject<HTMLElement | null>).current = el;

    if (boundRef.current && boundRef.current !== el && boundListenersRef.current) {
      unbindEventListeners(boundRef.current, boundListenersRef.current);
      boundRef.current = null;
      boundListenersRef.current = null;
    }

    if (el && boundRef.current !== el) {
      const listeners: Record<string, EventListenerObject> = {
        input: {
          handleEvent: (event: Event) => {
            propsRef.current.onInput?.(getCustomEventDetail<LxInputEventDetail>(event));
          }
        },
        change: {
          handleEvent: (event: Event) => {
            propsRef.current.onChange?.(getCustomEventDetail<LxInputEventDetail>(event));
          }
        },
        focus: {
          handleEvent: (event: Event) => {
            propsRef.current.onFocus?.(getCustomEventDetail<LxInputEventDetail>(event));
          }
        },
        blur: {
          handleEvent: (event: Event) => {
            propsRef.current.onBlur?.(getCustomEventDetail<LxInputEventDetail>(event));
          }
        },
        confirm: {
          handleEvent: (event: Event) => {
            propsRef.current.onConfirm?.(getCustomEventDetail<LxInputEventDetail>(event));
          }
        },
        keyboardheightchange: {
          handleEvent: (event: Event) => {
            propsRef.current.onKeyboardHeightChange?.(getCustomEventDetail<LxInputEventDetail>(event));
          }
        },
        nicknamereview: {
          handleEvent: (event: Event) => {
            propsRef.current.onNicknameReview?.(getCustomEventDetail<LxInputEventDetail>(event));
          }
        },
      };
      bindEventListeners(el, listeners);
      boundRef.current = el;
      boundListenersRef.current = listeners;
      hasMountedRef.current = true;
      return;
    }

    if (!el) {
      hasMountedRef.current = false;
    }
  }, [ref]);

  // React custom-element prop forwarding can be inconsistent for generic keys.
  // Force attribute sync so native side always receives the expected values.
  useEffect(() => {
    const el = boundRef.current;
    if (!el) return;
    const setAttr = (name: string, next: string | null) => {
      if (next === null || next === "") {
        el.removeAttribute(name);
        return;
      }
      el.setAttribute(name, next);
    };

    if (type && String(type).trim().length > 0) {
      el.setAttribute("type", String(type).trim().toLowerCase());
    } else {
      el.removeAttribute("type");
    }
    if (password) {
      el.setAttribute("password", "true");
    } else {
      el.removeAttribute("password");
    }
    setAttr("value", value !== undefined ? String(value) : null);
    setAttr("focus", focus !== undefined ? (focus ? "true" : "false") : null);
    setAttr("maxlength", maxlength !== undefined ? String(maxlength) : null);
    setAttr("placeholder-style", placeholderStyle ? String(placeholderStyle) : null);
    const syncNativeProps = (el as unknown as { syncNativeProps?: () => void }).syncNativeProps;
    if (didInitialNativeSyncRef.current && typeof syncNativeProps === "function") {
      syncNativeProps.call(el);
    } else {
      didInitialNativeSyncRef.current = true;
    }
  }, [type, password, value, focus, maxlength, placeholderStyle]);

  const inputProps: Record<string, string> = {};
  if (typeof id === "string" && id.trim().length > 0) {
    inputProps.id = id.trim();
  }
  if (value !== undefined) {
    inputProps.value = value;
  } else if (!hasMountedRef.current && initialValueRef.current !== undefined) {
    inputProps.value = initialValueRef.current;
  }
  if (type) inputProps.type = type;
  if (password) inputProps.password = "true";
  if (placeholder) inputProps.placeholder = placeholder;
  if (placeholderStyle) inputProps["placeholder-style"] = placeholderStyle;
  if (placeholderClass) inputProps["placeholder-class"] = placeholderClass;
  if (maxlength !== undefined) inputProps.maxlength = String(maxlength);
  if (cursorSpacing !== undefined) inputProps["cursor-spacing"] = String(cursorSpacing);
  if (autoFocus) inputProps["auto-focus"] = "true";
  if (disabled) inputProps.disabled = "true";
  if (focus !== undefined) inputProps.focus = focus ? "true" : "false";
  if (confirmType) inputProps["confirm-type"] = confirmType;
  if (alwaysEmbed) inputProps["always-embed"] = "true";
  if (confirmHold) inputProps["confirm-hold"] = "true";
  if (cursor !== undefined) inputProps.cursor = String(cursor);
  if (cursorColor) inputProps["cursor-color"] = cursorColor;
  if (selectionStart !== undefined) inputProps["selection-start"] = String(selectionStart);
  if (selectionEnd !== undefined) inputProps["selection-end"] = String(selectionEnd);
  if (adjustPosition === false) inputProps["adjust-position"] = "false";
  if (holdKeyboard) inputProps["hold-keyboard"] = "true";

  if (bindInput) inputProps.bindinput = bindInput;
  if (bindChange) inputProps.bindchange = bindChange;
  if (bindFocus) inputProps.bindfocus = bindFocus;
  if (bindBlur) inputProps.bindblur = bindBlur;
  if (bindConfirm) inputProps.bindconfirm = bindConfirm;
  if (bindKeyboardHeightChange) inputProps.bindkeyboardheightchange = bindKeyboardHeightChange;
  if (bindNicknameReview) inputProps.bindnicknamereview = bindNicknameReview;
  if (catchInput) inputProps.catchinput = catchInput;
  if (catchChange) inputProps.catchchange = catchChange;
  if (catchFocus) inputProps.catchfocus = catchFocus;
  if (catchBlur) inputProps.catchblur = catchBlur;
  if (catchConfirm) inputProps.catchconfirm = catchConfirm;
  if (catchKeyboardHeightChange) inputProps.catchkeyboardheightchange = catchKeyboardHeightChange;
  if (catchNicknameReview) inputProps.catchnicknamereview = catchNicknameReview;

  appendBindingAndDatasetAttrs(rest as Record<string, unknown>, inputProps);

  return React.createElement("lx-input", {
    ref: inputRefCallback,
    className,
    style,
    ...inputProps,
  });
});

LxInput.displayName = "LxInput";
