// lingxia-components/src/vue/LxNavigator.vue
<script setup lang="ts">
import { ref, h, onMounted, onBeforeUnmount } from 'vue';
import type { LxNavigatorEvent } from '../navigator.js';
import type { LxNavigatorProps } from './types.js';
import '../navigator.js';

const props = withDefaults(defineProps<LxNavigatorProps>(), {
  openType: 'navigate',
  delta: 1,
  hoverClass: 'navigator-hover',
  hoverStopPropagation: false,
  hoverStartTime: 20,
  hoverStayTime: 70,
});

const slots = defineSlots();

const emit = defineEmits<{
  success: [e: LxNavigatorEvent];
  fail: [e: LxNavigatorEvent];
  complete: [e: LxNavigatorEvent];
}>();

const elementRef = ref<HTMLElement | null>(null);

const handleSuccess = (e: Event) => emit('success', e as LxNavigatorEvent);
const handleFail = (e: Event) => emit('fail', e as LxNavigatorEvent);
const handleComplete = (e: Event) => emit('complete', e as LxNavigatorEvent);
const successListener: EventListenerObject = { handleEvent: handleSuccess };
const failListener: EventListenerObject = { handleEvent: handleFail };
const completeListener: EventListenerObject = { handleEvent: handleComplete };

onMounted(() => {
  const el = elementRef.value;
  if (!el) return;
  el.addEventListener('success', successListener);
  el.addEventListener('fail', failListener);
  el.addEventListener('complete', completeListener);
});

onBeforeUnmount(() => {
  const el = elementRef.value;
  if (!el) return;
  el.removeEventListener('success', successListener);
  el.removeEventListener('fail', failListener);
  el.removeEventListener('complete', completeListener);
});

defineExpose({ el: elementRef });

const render = () => h(
  'lx-navigator',
  {
    ref: elementRef,
    url: props.url,
    'open-type': props.openType,
    target: props.target,
    delta: String(props.delta),
    'lx-app-id': props.lxAppId,
    path: props.path,
    'phone-number': props.phoneNumber,
    'hover-class': props.hoverClass,
    'hover-stop-propagation': String(props.hoverStopPropagation),
    'hover-start-time': String(props.hoverStartTime),
    'hover-stay-time': String(props.hoverStayTime),
    class: props.class,
    style: props.style,
  },
  slots.default?.()
);
</script>

<template>
  <render />
</template>

// lingxia-components/src/react/LxNavigator.tsx
import React from 'react';
import type {
  LxNavigatorAttributes,
  LxNavigatorEvent,
  NavigatorOpenType,
  NavigatorTarget
} from '../navigator.js';

// Import to ensure custom element is registered
import '../navigator.js';

export interface LxNavigatorProps extends Omit<LxNavigatorAttributes, 'onSuccess' | 'onFail' | 'onComplete'> {
  // Navigation
  url?: string;
  openType?: NavigatorOpenType;
  target?: NavigatorTarget; // Auto-inferred if not specified
  delta?: number;

  // Open external lxapp
  lxAppId?: string;
  path?: string; // Supports query string

  // Phone call
  phoneNumber?: string;

  // Hover effect
  hoverClass?: string;
  hoverStopPropagation?: boolean;
  hoverStartTime?: number;
  hoverStayTime?: number;

  // Styling
  className?: string;
  style?: React.CSSProperties;

  // Events
  onSuccess?: (e: LxNavigatorEvent) => void;
  onFail?: (e: LxNavigatorEvent) => void;
  onComplete?: (e: LxNavigatorEvent) => void;

  // Children
  children?: React.ReactNode;
}

export const LxNavigator = React.forwardRef<HTMLElement, LxNavigatorProps>(
  (props, ref) => {
    const {
      url,
      openType = 'navigate',
      target, // Auto-inferred, no default
      delta = 1,
      lxAppId,
      path,
      phoneNumber,
      hoverClass = 'navigator-hover',
      hoverStopPropagation = false,
      hoverStartTime = 20,
      hoverStayTime = 70,
      className,
      style,
      onSuccess,
      onFail,
      onComplete,
      children,
      ...rest
    } = props;

    const elementRef = React.useRef<HTMLElement>(null);

    React.useImperativeHandle(ref, () => elementRef.current!);

    React.useEffect(() => {
      const element = elementRef.current;
      if (!element) return;

      const handleSuccess = (e: Event) => {
        if (onSuccess) {
          onSuccess(e as LxNavigatorEvent);
        }
      };

      const handleFail = (e: Event) => {
        if (onFail) {
          onFail(e as LxNavigatorEvent);
        }
      };

      const handleComplete = (e: Event) => {
        if (onComplete) {
          onComplete(e as LxNavigatorEvent);
        }
      };
      const successListener: EventListenerObject = { handleEvent: handleSuccess };
      const failListener: EventListenerObject = { handleEvent: handleFail };
      const completeListener: EventListenerObject = { handleEvent: handleComplete };

      element.addEventListener('success', successListener);
      element.addEventListener('fail', failListener);
      element.addEventListener('complete', completeListener);

      return () => {
        element.removeEventListener('success', successListener);
        element.removeEventListener('fail', failListener);
        element.removeEventListener('complete', completeListener);
      };
    }, [onSuccess, onFail, onComplete]);

    return React.createElement(
      'lx-navigator',
      {
        ref: elementRef,
        url,
        'open-type': openType,
        target, // Optional, will be auto-inferred if not specified
        delta: delta.toString(),
        'lx-app-id': lxAppId,
        path,
        'phone-number': phoneNumber,
        'hover-class': hoverClass,
        'hover-stop-propagation': hoverStopPropagation.toString(),
        'hover-start-time': hoverStartTime.toString(),
        'hover-stay-time': hoverStayTime.toString(),
        className,
        style,
        ...rest
      },
      children
    );
  }
);

LxNavigator.displayName = 'LxNavigator';
