// lingxia-components/src/vue/LxVideo.vue
<script setup lang="ts">
import { ref, computed, h, onMounted, onBeforeUnmount, useAttrs, useId, watch } from 'vue';
import { registerVideoComponent } from '../video.js';
import type { LxVideoProps } from './types.js';

const props = withDefaults(defineProps<LxVideoProps>(), {
  autoplay: false,
  loop: false,
  muted: false,
  controls: true,
  progressBar: true,
  live: false,
});
const attrs = useAttrs();

const emit = defineEmits<{
  playRequest: [e: Event];
  play: [e: Event];
  playing: [e: Event];
  pause: [e: Event];
  stop: [e: Event];
  ended: [e: Event];
  timeUpdate: [e: Event];
  error: [e: Event];
  loadedMetadata: [e: Event];
  fullscreenChange: [e: Event];
  waiting: [e: Event];
  qualityChange: [e: Event];
  rateChange: [e: Event];
}>();

if (typeof window !== 'undefined') {
  registerVideoComponent();
}

const elementRef = ref<HTMLElement | null>(null);
const handlerMap = ref(new Map<string, EventListenerOrEventListenerObject>());
const vueId = useId();

const resolvedId = computed(() => props.id || `lx-video-${vueId.replace(/[:]/g, '')}`);

const eventMap: Record<string, string> = {
  playRequest: 'playrequest',
  play: 'play',
  playing: 'playing',
  pause: 'pause',
  stop: 'stop',
  ended: 'ended',
  timeUpdate: 'timeupdate',
  error: 'error',
  loadedMetadata: 'loadedmetadata',
  fullscreenChange: 'fullscreenchange',
  waiting: 'waiting',
  qualityChange: 'qualitychange',
  rateChange: 'ratechange',
};

function normalizeBindingAttrName(key: string): string {
  return key.replace(/[^a-zA-Z0-9]/g, '').toLowerCase();
}

function setupEventListeners() {
  const el = elementRef.value;
  if (!el) return;
  for (const [eventName, handler] of handlerMap.value.entries()) {
    el.removeEventListener(eventName, handler);
  }
  handlerMap.value.clear();
  for (const [vueEvent, domEvent] of Object.entries(eventMap)) {
    const handler: EventListenerObject = {
      handleEvent: (e: Event) => emit(vueEvent as any, e),
    };
    el.addEventListener(domEvent, handler);
    handlerMap.value.set(domEvent, handler);
  }
}

function cleanupEventListeners() {
  const el = elementRef.value;
  if (!el) return;
  for (const [eventName, handler] of handlerMap.value.entries()) {
    el.removeEventListener(eventName, handler);
  }
  handlerMap.value.clear();
}

onMounted(setupEventListeners);
onBeforeUnmount(cleanupEventListeners);
watch(elementRef, setupEventListeners);

watch(
  [elementRef, () => props.rotate, () => props.objectFit],
  () => {
    const el = elementRef.value;
    if (!el) return;
    const rotate = props.rotate;
    if (rotate === undefined || rotate === null || rotate === '') {
      el.removeAttribute('rotate');
    } else {
      el.setAttribute('rotate', String(rotate).trim());
    }
    const objectFit = props.objectFit;
    if (objectFit === undefined || objectFit === null || objectFit === '') {
      el.removeAttribute('object-fit');
    } else {
      el.setAttribute('object-fit', String(objectFit).trim().toLowerCase());
    }
  },
  { immediate: true }
);

const domProps = computed(() => {
  const result: Record<string, any> = { id: resolvedId.value };
  if (props.src) result.src = props.src;
  if (props.poster) result.poster = props.poster;
  if (props.autoplay) result.autoplay = true;
  if (props.loop) result.loop = true;
  if (props.muted) result.muted = true;
  if (props.controls) result.controls = true;
  if (props.live) result.live = '';
  if (props.volume !== undefined) result.volume = props.volume;
  if (props.progressBar === false) result['progress-bar'] = 'false';
  if (props.qualities?.length) result.qualities = JSON.stringify(props.qualities);
  if (props.playbackRates?.length) result['playback-rates'] = JSON.stringify(props.playbackRates);
  for (const [key, value] of Object.entries(props as Record<string, unknown>)) {
    if (typeof value !== 'string') continue;
    if (key.startsWith('bind') || key.startsWith('catch')) {
      result[normalizeBindingAttrName(key)] = value;
    }
  }
  for (const [key, value] of Object.entries(attrs)) {
    if (typeof value !== 'string') continue;
    if (key.startsWith('data-')) {
      result[key] = value;
      continue;
    }
    if (key.startsWith('bind') || key.startsWith('catch')) {
      result[normalizeBindingAttrName(key)] = value;
    }
  }
  return result;
});

defineExpose({ el: elementRef });

const render = () => h('lx-video', { ref: elementRef, ...domProps.value, class: props.class });
</script>

<template>
  <render />
</template>

// lingxia-components/src/react/LxVideo.tsx
import React, { forwardRef, useEffect, useId, useMemo, useRef } from 'react';
import { registerVideoComponent, type LxVideoAttributes } from '../video.js';

export interface LxVideoProps
  extends LxVideoAttributes,
    Omit<
      React.HTMLAttributes<HTMLElement>,
      keyof LxVideoAttributes | "children" | "dangerouslySetInnerHTML" | "ref" | "onPlaying"
    > {}

// Ensure the custom element is registered exactly once when running in a browser
if (typeof window !== "undefined") {
  registerVideoComponent();
}

function normalizeBindingAttrName(key: string): string {
  return key.replace(/[^a-zA-Z0-9]/g, "").toLowerCase();
}

export const LxVideo = forwardRef<HTMLElement, LxVideoProps>((props, ref) => {
  const innerRef = useRef<HTMLElement>(null);
  const handlerRef = useRef<Map<string, EventListenerOrEventListenerObject>>(new Map());
  const reactId = useId();
  const resolvedId = useMemo(() => {
    if (props.id) return props.id;
    return `lx-video-${reactId.replace(/[:]/g, "")}`;
  }, [props.id, reactId]);
  const combinedRef = (node: HTMLElement | null) => {
    innerRef.current = node;
    if (!ref) return;
    if (typeof ref === "function") {
      ref(node);
    } else {
      (ref as React.MutableRefObject<HTMLElement | null>).current = node;
    }
  };

  // Handle events manually to bypass React synthetic event issues with Custom Elements
  useEffect(() => {
    const el = innerRef.current;
    if (!el) return;

    const prev = handlerRef.current;
    const next = new Map<string, EventListenerOrEventListenerObject>();

    for (const [key, value] of Object.entries(props)) {
      if (!key.startsWith("on") || typeof value !== "function") continue;
      const eventName = key.substring(2).toLowerCase();
      const listener: EventListenerObject = { handleEvent: value as EventListener };
      next.set(eventName, listener);
      const prevHandler = prev.get(eventName);
      if (prevHandler) el.removeEventListener(eventName, prevHandler);
      el.addEventListener(eventName, listener);
    }

    for (const [eventName, handler] of prev.entries()) {
      if (!next.has(eventName)) {
        el.removeEventListener(eventName, handler);
      }
    }

    handlerRef.current = next;
    return () => {
      for (const [eventName, handler] of next.entries()) {
        el.removeEventListener(eventName, handler);
      }
    };
  }, [props]);

  // Force attribute sync for custom-element props that React may treat inconsistently.
  useEffect(() => {
    const el = innerRef.current;
    if (!el) return;
    const rotate = props.rotate;
    if (rotate === undefined || rotate === null) {
      el.removeAttribute("rotate");
    } else {
      el.setAttribute("rotate", String(rotate).trim());
    }
    const objectFit = props.objectFit;
    if (objectFit === undefined || objectFit === null) {
      el.removeAttribute("object-fit");
    } else {
      el.setAttribute("object-fit", String(objectFit).trim().toLowerCase());
    }
  }, [props.rotate, props.objectFit]);

  // Filter out event props and React-only props before passing to the custom element
  const domProps: Record<string, any> = {};
  for (const [key, value] of Object.entries(props)) {
    if (key.startsWith("on")) continue;
    if ((key.startsWith("bind") || key.startsWith("catch")) && typeof value === "string") {
      domProps[normalizeBindingAttrName(key)] = value;
      continue;
    }
    if (key === "children" || key === "dangerouslySetInnerHTML" || key === "ref") continue;

    let attrName = key;
    if (key === "playbackRates") attrName = "playback-rates";
    if (key === "rotate") {
      // Synchronized via effect to avoid duplicate custom-element updates.
      continue;
    }
    if (key === "objectFit") {
      // Synchronized via effect to avoid duplicate custom-element updates.
      continue;
    }
    if (key === "progressBar") {
      if (value === false) {
        domProps["progress-bar"] = "false";
      }
      continue;
    }
    if (key === "live") {
      if (value === true) {
        domProps.live = "";
      }
      continue;
    }

    domProps[attrName] = (key === "qualities" || key === "playbackRates") && Array.isArray(value)
      ? JSON.stringify(value)
      : value;
  }
  domProps.id = resolvedId;

  // @ts-ignore - Custom element
  return React.createElement('lx-video', {
    ref: combinedRef,
    ...domProps
  });
});

LxVideo.displayName = 'LxVideo';
