// examples/lingxia-showcase/lxapp/pages/device/index.vue
<template>
  <div class="min-h-screen bg-linear-to-br from-surface-50 to-surface-100" data-testid="device-page" :data-mode="currentType">
    <div class="px-4 py-6">
      <!-- Device Info Section -->
      <template v-if="currentType === 'device' || !['device', 'screen', 'vibrate', 'dial', 'networkType', 'localIP', 'networkStatus', 'orientation'].includes(currentType)">
        <div class="mb-6 text-center">
          <h1 class="text-2xl font-light text-gray-800 mb-2">Device Information</h1>
          <div class="w-16 h-0.5 bg-surface-400 mx-auto"></div>
        </div>

        <div class="mb-5 bg-surface rounded-2xl shadow-sm border border-line-100 overflow-hidden">
          <div class="flex items-center gap-4 px-5 py-5 border-b border-line-100">
            <div class="flex items-center justify-center w-12 h-12 rounded-xl bg-linear-to-br from-blue-50 to-indigo-50">
              <span class="text-2xl">📱</span>
            </div>
            <div class="flex-1">
              <div class="text-sm text-gray-800 font-semibold">Get Device Information</div>
              <div class="text-xs text-gray-500 mt-0.5">Brand, model, and OS version</div>
            </div>
            <button
              data-testid="device-get-info"
              @click="getDeviceInfo"
              class="px-5 py-2.5 text-sm font-medium transition-all duration-200 bg-linear-to-r from-blue-600 to-blue-500 hover:from-blue-500 hover:to-blue-600 text-white rounded-xl shadow-sm active:scale-[0.98]"
            >
              Get Info
            </button>
          </div>

          <div v-if="deviceInfo" class="p-5" data-testid="device-info-result">
            <div class="rounded-xl border border-line-200 bg-linear-to-br from-surface-50 to-surface p-4">
              <div class="flex items-center gap-2 mb-4">
                <span class="w-1 h-4 bg-blue-500 rounded-full"></span>
                <h4 class="text-sm font-semibold text-gray-700">Device Information</h4>
              </div>
              <div class="flex justify-between items-center py-3 border-b border-line-200">
                <span class="text-sm text-gray-600">Brand</span>
                <span class="text-sm font-semibold text-gray-800 px-3 py-1 bg-blue-50 rounded-lg">{{ deviceInfo.brand || '--' }}</span>
              </div>
              <div class="flex justify-between items-center py-3 border-b border-line-200">
                <span class="text-sm text-gray-600">Market Name</span>
                <span class="text-sm font-semibold text-gray-800 px-3 py-1 bg-blue-50 rounded-lg">{{ deviceInfo.marketName || deviceInfo.model || '--' }}</span>
              </div>
              <div class="flex justify-between items-center py-3 border-b border-line-200">
                <span class="text-sm text-gray-600">Model</span>
                <span class="text-sm font-semibold text-gray-800 px-3 py-1 bg-blue-50 rounded-lg">{{ deviceInfo.model || '--' }}</span>
              </div>
              <div class="flex justify-between items-center py-3 border-b border-line-200">
                <span class="text-sm text-gray-600">OS Name</span>
                <span class="text-sm font-semibold text-gray-800 px-3 py-1 bg-blue-50 rounded-lg">{{ deviceInfo.osName || '--' }}</span>
              </div>
              <div class="flex justify-between items-center py-3">
                <span class="text-sm text-gray-600">OS Version</span>
                <span class="text-sm font-semibold text-gray-800 px-3 py-1 bg-blue-50 rounded-lg">{{ deviceInfo.osVersion || '--' }}</span>
              </div>
            </div>
          </div>
        </div>

        <div class="mb-5 bg-surface rounded-2xl shadow-sm border border-line-100 overflow-hidden">
          <div class="flex items-center gap-4 px-5 py-5 border-b border-line-100">
            <div class="flex items-center justify-center w-12 h-12 rounded-xl bg-linear-to-br from-cyan-50 to-sky-50">
              <span class="text-2xl">🌐</span>
            </div>
            <div class="flex-1">
              <div class="text-sm text-gray-800 font-semibold">Network Information</div>
              <div class="text-xs text-gray-500 mt-0.5">Get network info and listen for network changes</div>
            </div>
            <button
              @click="getNetworkInfo"
              class="px-5 py-2.5 text-sm font-medium transition-all duration-200 bg-linear-to-r from-cyan-600 to-cyan-500 hover:from-cyan-500 hover:to-cyan-600 text-white rounded-xl shadow-sm active:scale-[0.98]"
            >
              Get Info
            </button>
          </div>
          <div class="p-5 space-y-4">
            <div class="grid grid-cols-2 gap-3">
              <button
                @click="startNetworkChangeListen"
                class="py-3 text-sm font-medium transition-all duration-200 bg-linear-to-r from-green-600 to-green-500 hover:from-green-500 hover:to-green-600 text-white rounded-xl shadow-sm active:scale-[0.98]"
              >
                Start Listen
              </button>
              <button
                @click="stopNetworkChangeListen"
                class="py-3 text-sm font-medium transition-all duration-200 bg-linear-to-r from-surface-600 to-surface-500 hover:from-surface-500 hover:to-surface-600 text-white rounded-xl shadow-sm active:scale-[0.98]"
              >
                Stop Listen
              </button>
            </div>
            <div class="rounded-xl border border-line-200 bg-linear-to-br from-surface-50 to-surface p-4 text-xs text-gray-700">
              <div class="mb-2 font-semibold text-gray-800">Current</div>
              <pre class="whitespace-pre-wrap break-all">{{ formatJson(networkInfo) }}</pre>
              <div class="mb-2 mt-4 font-semibold text-gray-800">Last Change</div>
              <pre class="whitespace-pre-wrap break-all">{{ formatJson(networkChange) }}</pre>
            </div>
          </div>
        </div>
      </template>

      <!-- Screen Info Section -->
      <template v-if="currentType === 'screen'">
        <div class="mb-6 text-center">
          <h1 class="text-2xl font-light text-gray-800 mb-2">Screen Information</h1>
          <div class="w-16 h-0.5 bg-surface-400 mx-auto"></div>
        </div>

        <div class="mb-5 bg-surface rounded-2xl shadow-sm border border-line-100 overflow-hidden">
          <div class="flex items-center gap-4 px-5 py-5 border-b border-line-100">
            <div class="flex items-center justify-center w-12 h-12 rounded-xl bg-linear-to-br from-purple-50 to-pink-50">
              <span class="text-2xl">🖥️</span>
            </div>
            <div class="flex-1">
              <div class="text-sm text-gray-800 font-semibold">Get Screen Information</div>
              <div class="text-xs text-gray-500 mt-0.5">Screen dimensions and scale</div>
            </div>
            <button
              data-testid="device-screen-get-info"
              @click="getScreenInfo"
              class="px-5 py-2.5 text-sm font-medium transition-all duration-200 bg-linear-to-r from-blue-600 to-blue-500 hover:from-blue-500 hover:to-blue-600 text-white rounded-xl shadow-sm active:scale-[0.98]"
            >
              Get Info
            </button>
          </div>

          <div v-if="screenInfo" class="p-5" data-testid="device-screen-result">
            <div class="rounded-xl border border-line-200 bg-linear-to-br from-surface-50 to-surface p-4">
              <div class="flex items-center gap-2 mb-4">
                <span class="w-1 h-4 bg-purple-500 rounded-full"></span>
                <h4 class="text-sm font-semibold text-gray-700">Screen Information</h4>
              </div>
              <div class="flex justify-between items-center py-3 border-b border-line-200">
                <span class="text-sm text-gray-600">Width</span>
                <span class="text-sm font-semibold text-gray-800 px-3 py-1 bg-blue-50 rounded-lg">{{ formatNumber(screenInfo.width) }}px</span>
              </div>
              <div class="flex justify-between items-center py-3 border-b border-line-200">
                <span class="text-sm text-gray-600">Height</span>
                <span class="text-sm font-semibold text-gray-800 px-3 py-1 bg-blue-50 rounded-lg">{{ formatNumber(screenInfo.height) }}px</span>
              </div>
              <div class="flex justify-between items-center py-3">
                <span class="text-sm text-gray-600">Scale</span>
                <span class="text-sm font-semibold text-gray-800 px-3 py-1 bg-blue-50 rounded-lg">{{ formatNumber(screenInfo.scale) }}</span>
              </div>
            </div>
          </div>
        </div>
      </template>

      <!-- Vibrate Section -->
      <template v-if="currentType === 'vibrate'">
        <div class="mb-6 text-center">
          <h1 class="text-2xl font-light text-gray-800 mb-2">Device Vibration</h1>
          <div class="w-16 h-0.5 bg-surface-400 mx-auto"></div>
        </div>

        <div class="mb-5 bg-surface rounded-2xl shadow-sm border border-line-100 overflow-hidden">
          <div class="p-6">
            <div class="flex items-center gap-3 mb-4">
              <div class="flex items-center justify-center w-10 h-10 rounded-xl bg-linear-to-br from-green-50 to-emerald-50">
                <span class="text-xl">📳</span>
              </div>
              <div>
                <div class="text-sm text-gray-800 font-semibold">Trigger Vibration</div>
                <div class="text-xs text-gray-500 mt-0.5">Test short or long vibration</div>
              </div>
            </div>
            <div class="grid grid-cols-2 gap-3">
              <button
                @click="vibrateShort"
                class="py-3 text-sm font-medium transition-all duration-200 bg-linear-to-r from-blue-600 to-blue-500 hover:from-blue-500 hover:to-blue-600 text-white rounded-xl shadow-sm active:scale-[0.98]"
              >
                Short
              </button>
              <button
                @click="vibrateLong"
                class="py-3 text-sm font-medium transition-all duration-200 bg-linear-to-r from-indigo-600 to-indigo-500 hover:from-indigo-500 hover:to-indigo-600 text-white rounded-xl shadow-sm active:scale-[0.98]"
              >
                Long
              </button>
            </div>
          </div>
        </div>
      </template>

      <!-- Phone Call Section -->
      <template v-if="currentType === 'dial'">
        <div class="mb-6 text-center">
          <h1 class="text-2xl font-light text-gray-800 mb-2">Phone Call</h1>
          <div class="w-16 h-0.5 bg-surface-400 mx-auto"></div>
        </div>

        <div class="mb-5 bg-surface rounded-2xl shadow-sm border border-line-100 overflow-hidden">
          <div class="p-6">
            <div class="flex items-center gap-3 mb-5">
              <div class="flex items-center justify-center w-10 h-10 rounded-xl bg-linear-to-br from-orange-50 to-red-50">
                <span class="text-xl">📞</span>
              </div>
              <div>
                <div class="text-sm text-gray-800 font-semibold">Dial Phone Number</div>
                <div class="text-xs text-gray-500 mt-0.5">Initiate a native dialer call</div>
              </div>
            </div>
            <div class="space-y-3">
              <input
                type="tel"
                inputmode="tel"
                v-model="phoneNumber"
                class="w-full px-4 py-3 text-sm border border-line-200 rounded-xl bg-surface focus:outline-hidden focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all"
                placeholder="Enter phone number"
              />
              <button
                @click="handleDial"
                class="w-full py-3 text-sm font-medium transition-all duration-200 bg-linear-to-r from-blue-600 to-blue-500 hover:from-blue-500 hover:to-blue-600 text-white rounded-xl shadow-sm active:scale-[0.98]"
              >
                Call
              </button>
            </div>
          </div>
        </div>
      </template>

      <!-- Network Type Section -->
      <template v-if="currentType === 'networkType'">
        <div class="mb-6 text-center">
          <h1 class="text-2xl font-light text-gray-800 mb-2">Network Type</h1>
          <div class="w-16 h-0.5 bg-surface-400 mx-auto"></div>
        </div>

        <div class="mb-5 bg-surface rounded-2xl shadow-sm border border-line-100 overflow-hidden">
          <div class="flex items-center gap-4 px-5 py-5 border-b border-line-100">
            <div class="flex-1">
              <div class="text-sm text-gray-800 font-semibold">Get Network Type</div>
              <div class="text-xs text-gray-500 mt-0.5">none / unknown / wifi / 2g / 3g / 4g / 5g / ethernet</div>
            </div>
            <button
              data-testid="device-network-get-info"
              @click="getNetworkInfo"
              class="px-5 py-2.5 text-sm font-medium bg-blue-500 hover:bg-blue-600 text-white rounded-xl shadow-sm active:scale-[0.98]"
            >
              Get Info
            </button>
          </div>
          <div class="p-5" data-testid="device-network-result">
            <div class="rounded-xl border border-line-200 bg-linear-to-br from-surface-50 to-surface p-4 space-y-3">
              <div class="flex justify-between"><span>Connected</span><strong>{{ networkInfo?.isConnected === undefined ? '--' : (networkInfo.isConnected ? 'Yes' : 'No') }}</strong></div>
              <div class="flex justify-between"><span>Network Type</span><strong>{{ networkInfo?.networkType || '--' }}</strong></div>
            </div>
          </div>
        </div>
      </template>

      <!-- Local IP Section -->
      <template v-if="currentType === 'localIP'">
        <div class="mb-6 text-center">
          <h1 class="text-2xl font-light text-gray-800 mb-2">Local IP Addresses</h1>
          <div class="w-16 h-0.5 bg-surface-400 mx-auto"></div>
        </div>

        <div class="mb-5 bg-surface rounded-2xl shadow-sm border border-line-100 overflow-hidden">
          <div class="flex items-center gap-4 px-5 py-5 border-b border-line-100">
            <div class="flex-1">
              <div class="text-sm text-gray-800 font-semibold">Get Local IPs (IPv4 + IPv6)</div>
              <div class="text-xs text-gray-500 mt-0.5">Current active network addresses</div>
            </div>
            <button
              data-testid="device-network-get-info"
              @click="getNetworkInfo"
              class="px-5 py-2.5 text-sm font-medium bg-teal-500 hover:bg-teal-600 text-white rounded-xl shadow-sm active:scale-[0.98]"
            >
              Get IP
            </button>
          </div>
          <div class="p-5" data-testid="device-network-result">
            <div class="rounded-xl border border-line-200 bg-linear-to-br from-surface-50 to-surface p-4 space-y-3">
              <div class="flex justify-between gap-4"><span>IPv4</span><strong class="break-all text-right">{{ networkInfo?.ipv4?.length ? networkInfo.ipv4.join(', ') : '--' }}</strong></div>
              <div class="flex justify-between gap-4"><span>IPv6</span><strong class="break-all text-right">{{ networkInfo?.ipv6?.length ? networkInfo.ipv6.join(', ') : '--' }}</strong></div>
            </div>
          </div>
        </div>
      </template>

      <!-- Network Listener Section -->
      <template v-if="currentType === 'networkStatus'">
        <div class="mb-6 text-center">
          <h1 class="text-2xl font-light text-gray-800 mb-2">Network Status Listener</h1>
          <div class="w-16 h-0.5 bg-surface-400 mx-auto"></div>
        </div>

        <div class="mb-5 bg-surface rounded-2xl shadow-sm border border-line-100 overflow-hidden">
          <div class="p-6 space-y-4">
            <div class="grid grid-cols-2 gap-3">
              <button
                data-testid="device-network-listen-start"
                @click="startNetworkChangeListen"
                class="py-3 text-sm font-medium bg-green-500 hover:bg-green-600 text-white rounded-xl shadow-sm active:scale-[0.98]"
              >
                Start Listen
              </button>
              <button
                data-testid="device-network-listen-stop"
                @click="stopNetworkChangeListen"
                class="py-3 text-sm font-medium bg-surface-500 hover:bg-surface-600 text-white rounded-xl shadow-sm active:scale-[0.98]"
              >
                Stop Listen
              </button>
            </div>
            <div class="rounded-xl border border-line-200 bg-linear-to-br from-surface-50 to-surface p-4 space-y-3" data-testid="device-network-status">
              <div class="flex justify-between"><span>Listening</span><strong>{{ networkListening ? 'Yes' : 'No' }}</strong></div>
              <div class="flex justify-between"><span>Connected</span><strong>{{ networkChange?.isConnected === undefined ? '--' : (networkChange.isConnected ? 'Yes' : 'No') }}</strong></div>
              <div class="flex justify-between"><span>Network Type</span><strong>{{ networkChange?.networkType || '--' }}</strong></div>
            </div>
          </div>
        </div>
      </template>

      <!-- Device Orientation Section -->
      <template v-if="currentType === 'orientation'">
        <div class="mb-6 text-center">
          <h1 class="text-2xl font-light text-gray-800 mb-2">Device Orientation</h1>
          <div class="w-16 h-0.5 bg-surface-400 mx-auto"></div>
        </div>

        <div class="mb-5 bg-surface rounded-2xl shadow-sm border border-line-100 overflow-hidden">
          <div class="p-6 space-y-4">
            <div class="flex items-center gap-3">
              <div class="flex items-center justify-center w-10 h-10 rounded-xl bg-linear-to-br from-violet-50 to-indigo-50">
                <span class="text-xl">🧭</span>
              </div>
              <div>
                <div class="text-sm text-gray-800 font-semibold">setDeviceOrientation / onDeviceOrientationChange</div>
                <div class="text-xs text-gray-500 mt-0.5">Lock orientation and listen device orientation changes</div>
              </div>
            </div>

            <div class="grid grid-cols-2 gap-3">
              <button
                @click="setOrientationPortrait"
                class="py-3 text-sm font-medium transition-all duration-200 bg-linear-to-r from-violet-600 to-violet-500 hover:from-violet-500 hover:to-violet-600 text-white rounded-xl shadow-sm active:scale-[0.98]"
              >
                Lock Portrait
              </button>
              <button
                @click="setOrientationLandscape"
                class="py-3 text-sm font-medium transition-all duration-200 bg-linear-to-r from-indigo-600 to-indigo-500 hover:from-indigo-500 hover:to-indigo-600 text-white rounded-xl shadow-sm active:scale-[0.98]"
              >
                Lock Landscape
              </button>
            </div>

            <div class="grid grid-cols-2 gap-3">
              <button
                @click="startDeviceOrientationListen"
                class="py-3 text-sm font-medium transition-all duration-200 bg-linear-to-r from-green-600 to-green-500 hover:from-green-500 hover:to-green-600 text-white rounded-xl shadow-sm active:scale-[0.98]"
              >
                Start Listen
              </button>
              <button
                @click="stopDeviceOrientationListen"
                class="py-3 text-sm font-medium transition-all duration-200 bg-linear-to-r from-surface-600 to-surface-500 hover:from-surface-500 hover:to-surface-600 text-white rounded-xl shadow-sm active:scale-[0.98]"
              >
                Stop Listen
              </button>
            </div>

            <div class="rounded-xl border border-line-200 bg-linear-to-br from-surface-50 to-surface p-4">
              <div class="flex justify-between items-center py-3 border-b border-line-200">
                <span class="text-sm text-gray-600">Listening</span>
                <span class="text-sm font-semibold text-gray-800 px-3 py-1 bg-blue-50 rounded-lg">{{ orientationListening ? 'Yes' : 'No' }}</span>
              </div>
              <div class="flex justify-between items-center py-3 border-b border-line-200">
                <span class="text-sm text-gray-600">Lock Target</span>
                <span class="text-sm font-semibold text-gray-800 px-3 py-1 bg-blue-50 rounded-lg">{{ orientationLock || '--' }}</span>
              </div>
              <div class="flex justify-between items-center py-3">
                <span class="text-sm text-gray-600">Current Value</span>
                <span class="text-sm font-semibold text-gray-800 px-3 py-1 bg-blue-50 rounded-lg">{{ deviceOrientationValue || '--' }}</span>
              </div>
            </div>

            <div class="rounded-xl border border-line-200 bg-linear-to-br from-surface-50 to-surface p-4">
              <div class="flex items-center justify-between mb-3">
                <h4 class="text-sm font-semibold text-gray-700">Orientation Events</h4>
                <button
                  @click="clearOrientationEvents"
                  class="px-3 py-1.5 text-xs font-medium transition-all duration-200 bg-linear-to-r from-surface-600 to-surface-500 hover:from-surface-500 hover:to-surface-600 text-white rounded-lg shadow-sm active:scale-[0.98]"
                >
                  Clear Logs
                </button>
              </div>
              <div class="text-xs text-gray-700 bg-surface border border-line-200 rounded-lg p-3 max-h-56 overflow-auto whitespace-pre-wrap break-all">
                {{ orientationEventsText }}
              </div>
            </div>
          </div>
        </div>
      </template>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import { useLxPage } from '@lingxia/vue';
import '../../tailwind.css';

const { data, actions } = useLxPage();
const {
  getDeviceInfo,
  getScreenInfo,
  vibrateShort,
  vibrateLong,
  makePhoneCall,
  setOrientationPortrait,
  setOrientationLandscape,
  startDeviceOrientationListen,
  stopDeviceOrientationListen,
  clearOrientationEvents,
  getNetworkInfo,
  startNetworkChangeListen,
  stopNetworkChangeListen,
} = actions;

const phoneNumber = ref('');

const currentType = computed(() => data.currentType ?? 'device');
const deviceInfo = computed(() => data.deviceInfo ?? null);
const screenInfo = computed(() => data.screenInfo ?? null);
const orientationListening = computed(() => data.orientationListening ?? false);
const orientationLock = computed(() => data.orientationLock ?? '');
const deviceOrientationValue = computed(() => data.deviceOrientationValue ?? '');
const orientationEvents = computed(() => Array.isArray(data.orientationEvents) ? data.orientationEvents : []);
const orientationEventsText = computed(() => orientationEvents.value.length ? orientationEvents.value.join('\n') : '--');
const networkInfo = computed(() => data.networkInfo ?? null);
const networkChange = computed(() => data.networkChange ?? null);
const networkListening = computed(() => data.networkListening ?? false);

watch(currentType, () => {
  phoneNumber.value = '';
});

function handleDial() {
  const trimmed = phoneNumber.value.trim();
  if (!trimmed) {
    return;
  }
  makePhoneCall({ phoneNumber: trimmed });
}

function formatNumber(value: number | undefined): string {
  if (typeof value !== 'number' || Number.isNaN(value)) {
    return '--';
  }
  return Number.isInteger(value) ? value.toString() : value.toFixed(2);
}

function formatJson(value: unknown): string {
  if (value === null || value === undefined) return '--';
  try {
    return JSON.stringify(value, null, 2);
  } catch (_error) {
    return String(value);
  }
}

</script>

// examples/lingxia-showcase/lxapp/pages/device/index.tsx
import React from 'react';
import { useLxPage } from '@lingxia/react';
import '../../tailwind.css';

export default function DevicePage() {
  const { data, actions } = useLxPage();
  const {
    getDeviceInfo,
    getScreenInfo,
    vibrateShort,
    vibrateLong,
    makePhoneCall,
    getNetworkInfo,
    startNetworkChangeListen,
    stopNetworkChangeListen,
    setOrientationPortrait,
    setOrientationLandscape,
    startDeviceOrientationListen,
    stopDeviceOrientationListen,
    clearOrientationEvents,
  } = actions;

  const {
    currentType = 'device',
    deviceInfo = null,
    screenInfo = null,
    networkInfo = null,
    networkChange = null,
    networkListening = false,
    orientationListening = false,
    deviceOrientationValue = '--',
    orientationEvents = [],
    orientationLock = '--',
  } = data;
  const orientationEventLines = Array.isArray(orientationEvents) ? orientationEvents : [];
  const [phoneNumber, setPhoneNumber] = React.useState('');

  React.useEffect(() => {
    setPhoneNumber('');
  }, [currentType]);

  const handleDial = React.useCallback(async () => {
    const trimmed = phoneNumber.trim();
    if (!trimmed) {
      return;
    }

    try {
      await makePhoneCall({ phoneNumber: trimmed });
    } catch (error) {
      console.error('makePhoneCall failed:', error);
    }
  }, [phoneNumber, makePhoneCall]);

  const renderDeviceInfoSection = () => (
    <>
      <div className="mb-6 text-center">
        <h1 className="text-2xl font-light text-gray-800 mb-2">Device Information</h1>
        <div className="w-16 h-0.5 bg-surface-400 mx-auto"></div>
      </div>

      <div className="mb-5 bg-surface rounded-2xl shadow-sm border border-line-100 overflow-hidden">
        <div className="flex items-center gap-4 px-5 py-5 border-b border-line-100">
          <div className="flex items-center justify-center w-12 h-12 rounded-xl bg-linear-to-br from-blue-50 to-indigo-50">
            <span className="text-2xl">📱</span>
          </div>
          <div className="flex-1">
            <div className="text-sm text-gray-800 font-semibold">Get Device Information</div>
            <div className="text-xs text-gray-500 mt-0.5">Brand, model, and OS version</div>
          </div>
          <button
            data-testid="device-get-info"
            onClick={getDeviceInfo}
            className="px-5 py-2.5 text-sm font-medium transition-all duration-200 bg-linear-to-r from-blue-600 to-blue-500 hover:from-blue-500 hover:to-blue-600 text-white rounded-xl shadow-sm active:scale-[0.98]"
          >
            Get Info
          </button>
        </div>

        {deviceInfo && (
          <div className="p-5" data-testid="device-info-result">
            <div className="rounded-xl border border-line-200 bg-linear-to-br from-surface-50 to-surface p-4">
              <div className="flex items-center gap-2 mb-4">
                <span className="w-1 h-4 bg-blue-500 rounded-full"></span>
                <h4 className="text-sm font-semibold text-gray-700">Device Information</h4>
              </div>
              <div className="space-y-0">
                <InfoRow label="Brand" value={deviceInfo.brand} />
                <InfoRow label="Market Name" value={deviceInfo.marketName || deviceInfo.model} />
                <InfoRow label="Model" value={deviceInfo.model} />
                <InfoRow label="OS Name" value={deviceInfo.osName} />
                <InfoRow label="OS Version" value={deviceInfo.osVersion} />
              </div>
            </div>
          </div>
        )}
      </div>
    </>
  );

  const renderScreenInfoSection = () => (
    <>
      <div className="mb-6 text-center">
        <h1 className="text-2xl font-light text-gray-800 mb-2">Screen Information</h1>
        <div className="w-16 h-0.5 bg-surface-400 mx-auto"></div>
      </div>

      <div className="mb-5 bg-surface rounded-2xl shadow-sm border border-line-100 overflow-hidden">
        <div className="flex items-center gap-4 px-5 py-5 border-b border-line-100">
          <div className="flex items-center justify-center w-12 h-12 rounded-xl bg-linear-to-br from-purple-50 to-pink-50">
            <span className="text-2xl">🖥️</span>
          </div>
          <div className="flex-1">
            <div className="text-sm text-gray-800 font-semibold">Get Screen Information</div>
            <div className="text-xs text-gray-500 mt-0.5">Screen dimensions and scale</div>
          </div>
          <button
            data-testid="device-screen-get-info"
            onClick={getScreenInfo}
            className="px-5 py-2.5 text-sm font-medium transition-all duration-200 bg-linear-to-r from-blue-600 to-blue-500 hover:from-blue-500 hover:to-blue-600 text-white rounded-xl shadow-sm active:scale-[0.98]"
          >
            Get Info
          </button>
        </div>

        {screenInfo && (
          <div className="p-5" data-testid="device-screen-result">
            <div className="rounded-xl border border-line-200 bg-linear-to-br from-surface-50 to-surface p-4">
              <div className="flex items-center gap-2 mb-4">
                <span className="w-1 h-4 bg-purple-500 rounded-full"></span>
                <h4 className="text-sm font-semibold text-gray-700">Screen Information</h4>
              </div>
              <div className="space-y-0">
                <InfoRow label="Width" value={formatNumber(screenInfo.width)} suffix="px" />
                <InfoRow label="Height" value={formatNumber(screenInfo.height)} suffix="px" />
                <InfoRow label="Scale" value={formatNumber(screenInfo.scale)} />
              </div>
            </div>
          </div>
        )}
      </div>
    </>
  );

  const renderVibrationSection = () => (
    <>
      <div className="mb-6 text-center">
        <h1 className="text-2xl font-light text-gray-800 mb-2">Device Vibration</h1>
        <div className="w-16 h-0.5 bg-surface-400 mx-auto"></div>
      </div>

      <div className="mb-5 bg-surface rounded-2xl shadow-sm border border-line-100 overflow-hidden">
        <div className="p-6">
          <div className="flex items-center gap-3 mb-4">
            <div className="flex items-center justify-center w-10 h-10 rounded-xl bg-linear-to-br from-green-50 to-emerald-50">
              <span className="text-xl">📳</span>
            </div>
            <div>
              <div className="text-sm text-gray-800 font-semibold">Trigger Vibration</div>
              <div className="text-xs text-gray-500 mt-0.5">Test short or long vibration</div>
            </div>
          </div>
          <div className="grid grid-cols-2 gap-3">
            <button
              onClick={vibrateShort}
              className="py-3 text-sm font-medium transition-all duration-200 bg-linear-to-r from-blue-600 to-blue-500 hover:from-blue-500 hover:to-blue-600 text-white rounded-xl shadow-sm active:scale-[0.98]"
            >
              Short
            </button>
            <button
              onClick={vibrateLong}
              className="py-3 text-sm font-medium transition-all duration-200 bg-linear-to-r from-indigo-600 to-indigo-500 hover:from-indigo-500 hover:to-indigo-600 text-white rounded-xl shadow-sm active:scale-[0.98]"
            >
              Long
            </button>
          </div>
        </div>
      </div>
    </>
  );

  const renderDialSection = () => (
    <>
      <div className="mb-6 text-center">
        <h1 className="text-2xl font-light text-gray-800 mb-2">Phone Call</h1>
        <div className="w-16 h-0.5 bg-surface-400 mx-auto"></div>
      </div>

      <div className="mb-5 bg-surface rounded-2xl shadow-sm border border-line-100 overflow-hidden">
        <div className="p-6">
          <div className="flex items-center gap-3 mb-5">
            <div className="flex items-center justify-center w-10 h-10 rounded-xl bg-linear-to-br from-orange-50 to-red-50">
              <span className="text-xl">📞</span>
            </div>
            <div>
              <div className="text-sm text-gray-800 font-semibold">Dial Phone Number</div>
              <div className="text-xs text-gray-500 mt-0.5">Initiate a native dialer call</div>
            </div>
          </div>
          <div className="space-y-3">
            <input
              type="tel"
              inputMode="tel"
              value={phoneNumber}
              onChange={(event) => setPhoneNumber(event.target.value)}
              className="w-full px-4 py-3 text-sm border border-line-200 rounded-xl bg-surface focus:outline-hidden focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all"
              placeholder="Enter phone number"
            />
            <button
              onClick={handleDial}
              className="w-full py-3 text-sm font-medium transition-all duration-200 bg-linear-to-r from-blue-600 to-blue-500 hover:from-blue-500 hover:to-blue-600 text-white rounded-xl shadow-sm active:scale-[0.98]"
            >
              Call
            </button>
          </div>
        </div>
      </div>
    </>
  );

  const renderNetworkTypeSection = () => (
    <>
      <div className="mb-6 text-center">
        <h1 className="text-2xl font-light text-gray-800 mb-2">Network Type</h1>
        <div className="w-16 h-0.5 bg-surface-400 mx-auto"></div>
      </div>

      <div className="mb-5 bg-surface rounded-2xl shadow-sm border border-line-100 overflow-hidden">
        <div className="flex items-center gap-4 px-5 py-5 border-b border-line-100">
          <div className="flex items-center justify-center w-12 h-12 rounded-xl bg-linear-to-br from-cyan-50 to-sky-50">
            <span className="text-2xl">🌐</span>
          </div>
          <div className="flex-1">
            <div className="text-sm text-gray-800 font-semibold">Get Network Type</div>
            <div className="text-xs text-gray-500 mt-0.5">none / unknown / wifi / 2g / 3g / 4g / 5g / ethernet</div>
          </div>
          <button
            data-testid="device-network-get-info"
            onClick={getNetworkInfo}
            className="px-5 py-2.5 text-sm font-medium transition-all duration-200 bg-linear-to-r from-blue-600 to-blue-500 hover:from-blue-500 hover:to-blue-600 text-white rounded-xl shadow-sm active:scale-[0.98]"
          >
            Get Info
          </button>
        </div>

        <div className="p-5" data-testid="device-network-result">
          <div className="rounded-xl border border-line-200 bg-linear-to-br from-surface-50 to-surface p-4">
            <InfoRow label="Connected" value={networkInfo?.isConnected === undefined ? '--' : (networkInfo.isConnected ? 'Yes' : 'No')} />
            <InfoRow label="Network Type" value={networkInfo?.networkType || '--'} />
          </div>
        </div>
      </div>
    </>
  );

  const renderLocalIPSection = () => (
    <>
      <div className="mb-6 text-center">
        <h1 className="text-2xl font-light text-gray-800 mb-2">Local IP Addresses</h1>
        <div className="w-16 h-0.5 bg-surface-400 mx-auto"></div>
      </div>

      <div className="mb-5 bg-surface rounded-2xl shadow-sm border border-line-100 overflow-hidden">
        <div className="flex items-center gap-4 px-5 py-5 border-b border-line-100">
          <div className="flex items-center justify-center w-12 h-12 rounded-xl bg-linear-to-br from-teal-50 to-emerald-50">
            <span className="text-2xl">📡</span>
          </div>
          <div className="flex-1">
            <div className="text-sm text-gray-800 font-semibold">Get Local IPs (IPv4 + IPv6)</div>
            <div className="text-xs text-gray-500 mt-0.5">Current active network addresses</div>
          </div>
          <button
            data-testid="device-network-get-info"
            onClick={getNetworkInfo}
            className="px-5 py-2.5 text-sm font-medium transition-all duration-200 bg-linear-to-r from-teal-600 to-teal-500 hover:from-teal-500 hover:to-teal-600 text-white rounded-xl shadow-sm active:scale-[0.98]"
          >
            Get IP
          </button>
        </div>

        <div className="p-5" data-testid="device-network-result">
          <div className="rounded-xl border border-line-200 bg-linear-to-br from-surface-50 to-surface p-4">
            <InfoRow label="IPv4" value={networkInfo?.ipv4?.length ? networkInfo.ipv4 : '--'} />
            <InfoRow label="IPv6" value={networkInfo?.ipv6?.length ? networkInfo.ipv6 : '--'} />
          </div>
        </div>
      </div>
    </>
  );

  const renderNetworkStatusSection = () => (
    <>
      <div className="mb-6 text-center">
        <h1 className="text-2xl font-light text-gray-800 mb-2">Network Status Listener</h1>
        <div className="w-16 h-0.5 bg-surface-400 mx-auto"></div>
      </div>

      <div className="mb-5 bg-surface rounded-2xl shadow-sm border border-line-100 overflow-hidden">
        <div className="p-6 space-y-4">
          <div className="grid grid-cols-2 gap-3">
            <button
              data-testid="device-network-listen-start"
              onClick={startNetworkChangeListen}
              className="py-3 text-sm font-medium transition-all duration-200 bg-linear-to-r from-green-600 to-green-500 hover:from-green-500 hover:to-green-600 text-white rounded-xl shadow-sm active:scale-[0.98]"
            >
              Start Listen
            </button>
            <button
              data-testid="device-network-listen-stop"
              onClick={stopNetworkChangeListen}
              className="py-3 text-sm font-medium transition-all duration-200 bg-linear-to-r from-surface-600 to-surface-500 hover:from-surface-500 hover:to-surface-600 text-white rounded-xl shadow-sm active:scale-[0.98]"
            >
              Stop Listen
            </button>
          </div>

          <div className="rounded-xl border border-line-200 bg-linear-to-br from-surface-50 to-surface p-4" data-testid="device-network-status">
            <InfoRow label="Listening" value={networkListening ? 'Yes' : 'No'} />
            <InfoRow label="Connected" value={networkChange?.isConnected === undefined ? '--' : (networkChange.isConnected ? 'Yes' : 'No')} />
            <InfoRow label="Network Type" value={networkChange?.networkType || '--'} />
            <InfoRow label="IPv4" value={networkChange?.ipv4?.length ? networkChange.ipv4 : '--'} />
            <InfoRow label="IPv6" value={networkChange?.ipv6?.length ? networkChange.ipv6 : '--'} />
          </div>
        </div>
      </div>
    </>
  );

  const renderOrientationSection = () => (
    <>
      <div className="mb-6 text-center">
        <h1 className="text-2xl font-light text-gray-800 mb-2">Device Orientation</h1>
        <div className="w-16 h-0.5 bg-surface-400 mx-auto"></div>
      </div>

      <div className="mb-5 bg-surface rounded-2xl shadow-sm border border-line-100 overflow-hidden">
        <div className="p-6 space-y-4">
          <div className="flex items-center gap-3">
            <div className="flex items-center justify-center w-10 h-10 rounded-xl bg-linear-to-br from-violet-50 to-indigo-50">
              <span className="text-xl">🧭</span>
            </div>
            <div>
              <div className="text-sm text-gray-800 font-semibold">setDeviceOrientation / onDeviceOrientationChange</div>
              <div className="text-xs text-gray-500 mt-0.5">Lock orientation and listen device orientation changes</div>
            </div>
          </div>

          <div className="grid grid-cols-2 gap-3">
            <button
              onClick={setOrientationPortrait}
              className="py-3 text-sm font-medium transition-all duration-200 bg-linear-to-r from-violet-600 to-violet-500 hover:from-violet-500 hover:to-violet-600 text-white rounded-xl shadow-sm active:scale-[0.98]"
            >
              Lock Portrait
            </button>
            <button
              onClick={setOrientationLandscape}
              className="py-3 text-sm font-medium transition-all duration-200 bg-linear-to-r from-indigo-600 to-indigo-500 hover:from-indigo-500 hover:to-indigo-600 text-white rounded-xl shadow-sm active:scale-[0.98]"
            >
              Lock Landscape
            </button>
          </div>

          <div className="grid grid-cols-2 gap-3">
            <button
              onClick={startDeviceOrientationListen}
              className="py-3 text-sm font-medium transition-all duration-200 bg-linear-to-r from-green-600 to-green-500 hover:from-green-500 hover:to-green-600 text-white rounded-xl shadow-sm active:scale-[0.98]"
            >
              Start Listen
            </button>
            <button
              onClick={stopDeviceOrientationListen}
              className="py-3 text-sm font-medium transition-all duration-200 bg-linear-to-r from-surface-600 to-surface-500 hover:from-surface-500 hover:to-surface-600 text-white rounded-xl shadow-sm active:scale-[0.98]"
            >
              Stop Listen
            </button>
          </div>

          <div className="rounded-xl border border-line-200 bg-linear-to-br from-surface-50 to-surface p-4">
            <InfoRow label="Listening" value={orientationListening ? 'Yes' : 'No'} />
            <InfoRow label="Lock Target" value={orientationLock || '--'} />
            <InfoRow label="Current Value" value={deviceOrientationValue || '--'} />
          </div>

          <div className="rounded-xl border border-line-200 bg-linear-to-br from-surface-50 to-surface p-4">
            <div className="flex items-center justify-between mb-3">
              <h4 className="text-sm font-semibold text-gray-700">Orientation Events</h4>
              <button
                onClick={clearOrientationEvents}
                className="px-3 py-1.5 text-xs font-medium transition-all duration-200 bg-linear-to-r from-surface-600 to-surface-500 hover:from-surface-500 hover:to-surface-600 text-white rounded-lg shadow-sm active:scale-[0.98]"
              >
                Clear Logs
              </button>
            </div>
            <div className="text-xs text-gray-700 bg-surface border border-line-200 rounded-lg p-3 max-h-56 overflow-auto whitespace-pre-wrap break-all">
              {orientationEventLines.length ? orientationEventLines.join('\n') : '--'}
            </div>
          </div>
        </div>
      </div>
    </>
  );

  return (
    <div className="min-h-screen bg-linear-to-br from-surface-50 to-surface-100" data-testid="device-page" data-mode={currentType}>
      <div className="px-4 py-6">
        {currentType === 'device' && renderDeviceInfoSection()}
        {currentType === 'screen' && renderScreenInfoSection()}
        {currentType === 'vibrate' && renderVibrationSection()}
        {currentType === 'dial' && renderDialSection()}
        {currentType === 'networkType' && renderNetworkTypeSection()}
        {currentType === 'localIP' && renderLocalIPSection()}
        {currentType === 'networkStatus' && renderNetworkStatusSection()}
        {currentType === 'orientation' && renderOrientationSection()}

        {!['device', 'screen', 'vibrate', 'dial', 'networkType', 'localIP', 'networkStatus', 'orientation'].includes(currentType) && renderDeviceInfoSection()}
      </div>
    </div>
  );
}

interface InfoRowProps {
  label: string;
  value?: string | number | string[];
  suffix?: string;
}

function InfoRow({ label, value, suffix }: InfoRowProps) {
  const display = value === undefined || value === null || value === '' ? '--' : value;
  const text = suffix && display !== '--' ? `${display}${suffix}` : display;
  const textContent = Array.isArray(text) ? text.join('\n') : String(text);
  return (
    <div className="flex justify-between items-start gap-3 py-3 border-b border-line-200 last:border-b-0">
      <span className="text-sm text-gray-600 shrink-0">{label}</span>
      <span className="text-sm font-semibold text-gray-800 px-3 py-1 bg-blue-50 rounded-lg text-right max-w-[72%] whitespace-pre-wrap break-all">
        {textContent}
      </span>
    </div>
  );
}

function formatNumber(value: number | undefined): string {
  if (typeof value !== 'number' || Number.isNaN(value)) {
    return '--';
  }
  return Number.isInteger(value) ? value.toString() : value.toFixed(2);
}
