// tools/lingxia-cli/templates/lxapp-create/react/pages/home/index.tsx
import React from 'react';
import { LxNavigator } from '@lingxia/components/react';
import { useLingXia } from '@lingxia/web-runtime/react';
import '../../app.css';

type PageState = { greeting: string; greetCount: number };
type PageActions = { greet(payload: { name: string }): void };

export default function HomePage() {
  const { data, greet } = useLingXia<PageState, PageActions>();
  const [name, setName] = React.useState('');
  const submit = () => name.trim() && greet({ name: name.trim() });

  return (
    <div style={S.page}>
      <div style={S.card}>
        <img src="/public/AppIcon.png" style={S.logo} />
        <h1 style={S.title}>Hello, LingXia</h1>
        <p style={S.subtitle}>Build once, run everywhere</p>

        <div style={S.form}>
          <input
            value={name}
            placeholder="Enter your name"
            onChange={e => setName(e.target.value)}
            onKeyDown={e => e.key === 'Enter' && submit()}
            style={S.input}
          />
          <button onClick={submit} disabled={!name.trim()} style={S.btn}>
            Say Hello
          </button>
        </div>

        {data.greeting && <p style={S.greeting}>{data.greeting}</p>}

        <div style={S.footer}>
          <LxNavigator url="https://www.lingxia.app" style={S.link}>
            Documentation →
          </LxNavigator>
        </div>
      </div>
    </div>
  );
}

const S: Record<string, React.CSSProperties> = {
  page: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  card: {
    width: '100%',
    maxWidth: 360,
    padding: 32,
    background: '#fff',
    borderRadius: 20,
    boxShadow: '0 4px 24px rgba(0,0,0,0.08)',
    textAlign: 'center',
  },
  logo: {
    width: 72,
    height: 72,
    borderRadius: 16,
    boxShadow: '0 2px 12px rgba(0,0,0,0.1)',
  },
  title: {
    margin: '20px 0 6px',
    fontSize: 26,
    fontWeight: 700,
    color: '#1d1d1f',
  },
  subtitle: {
    margin: 0,
    fontSize: 15,
    color: '#86868b',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
    marginTop: 28,
  },
  input: {
    width: '100%',
    height: 48,
    padding: '0 16px',
    border: '1px solid #d2d2d7',
    borderRadius: 12,
    fontSize: 16,
    outline: 'none',
    background: '#fafafa',
    transition: 'border-color 0.2s',
  },
  btn: {
    width: '100%',
    height: 48,
    border: 'none',
    borderRadius: 12,
    background: '#007aff',
    color: '#fff',
    fontSize: 16,
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'background 0.2s',
  },
  greeting: {
    marginTop: 24,
    padding: 16,
    background: '#f0fdf4',
    border: '1px solid #bbf7d0',
    borderRadius: 12,
    color: '#166534',
    fontSize: 15,
    whiteSpace: 'pre-line',
    textAlign: 'left',
  },
  footer: {
    marginTop: 28,
    paddingTop: 20,
    borderTop: '1px solid #f0f0f0',
  },
  link: {
    color: '#007aff',
    fontSize: 14,
    fontWeight: 500,
    textDecoration: 'none',
  },
};

// tools/lingxia-cli/templates/lxapp-create/vue/pages/home/index.vue
<script setup lang="ts">
import '../../app.css';
import { LxNavigator } from '@lingxia/components/vue';
import { useLingXia } from '@lingxia/web-runtime/vue';
import { computed, ref } from 'vue';

type PageState = { greeting?: string; greetCount?: number };
type PageActions = { greet(payload: { name: string }): void };

const { data, greet } = useLingXia<PageState, PageActions>();
const state = computed(() => data ?? { greeting: '', greetCount: 0 });
const inputName = ref('');
const canSubmit = computed(() => inputName.value.trim().length > 0);

function handleSubmit() {
  const v = inputName.value.trim();
  if (v) greet({ name: v });
}
</script>

<template>
  <div class="page">
    <div class="card">
      <img :src="'/public/AppIcon.png'" class="logo" />
      <h1 class="title">Hello, LingXia</h1>
      <p class="subtitle">Build once, run everywhere</p>

      <div class="form">
        <input v-model="inputName" placeholder="Enter your name" class="input" @keydown.enter.prevent="handleSubmit" />
        <button :disabled="!canSubmit" class="btn" @click="handleSubmit">Say Hello</button>
      </div>

      <p v-if="state.greeting" class="greeting">{{ state.greeting }}</p>

      <div class="footer">
        <LxNavigator url="https://www.lingxia.app" class="link">
          Documentation →
        </LxNavigator>
      </div>
    </div>
  </div>
</template>

<style scoped>
.page {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 20px;
}
.card {
  width: 100%;
  max-width: 360px;
  padding: 32px;
  background: #fff;
  border-radius: 20px;
  box-shadow: 0 4px 24px rgba(0,0,0,0.08);
  text-align: center;
}
.logo {
  width: 72px;
  height: 72px;
  border-radius: 16px;
  box-shadow: 0 2px 12px rgba(0,0,0,0.1);
}
.title {
  margin: 20px 0 6px;
  font-size: 26px;
  font-weight: 700;
  color: #1d1d1f;
}
.subtitle {
  margin: 0;
  font-size: 15px;
  color: #86868b;
}
.form {
  display: flex;
  flex-direction: column;
  gap: 12px;
  margin-top: 28px;
}
.input {
  width: 100%;
  height: 48px;
  padding: 0 16px;
  border: 1px solid #d2d2d7;
  border-radius: 12px;
  font-size: 16px;
  outline: none;
  background: #fafafa;
  transition: border-color 0.2s;
}
.input:focus {
  border-color: #007aff;
}
.btn {
  width: 100%;
  height: 48px;
  border: none;
  border-radius: 12px;
  background: #007aff;
  color: #fff;
  font-size: 16px;
  font-weight: 600;
  cursor: pointer;
  transition: background 0.2s;
}
.btn:hover:not(:disabled) {
  background: #0066d6;
}
.btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}
.greeting {
  margin-top: 24px;
  padding: 16px;
  background: #f0fdf4;
  border: 1px solid #bbf7d0;
  border-radius: 12px;
  color: #166534;
  font-size: 15px;
  white-space: pre-line;
  text-align: left;
}
.footer {
  margin-top: 28px;
  padding-top: 20px;
  border-top: 1px solid #f0f0f0;
}
.link {
  color: #007aff;
  font-size: 14px;
  font-weight: 500;
  text-decoration: none;
}
</style>
