// packages/lingxia-react/src/native/LxNativeSlider.tsx
import React, { forwardRef, useCallback, useEffect, useRef } from "react";
import {
  registerNativeSliderComponent,
  type NativeHandler,
  type ValuePayload,
  type FocusPayload,
  type PointerPayload,
} from "@lingxia/elements";
import {
  assignNativeRef,
  bindNativeEvents,
  payloadListener,
  setOptionalAttribute,
  type LxNativeNodeProps,
} from "./shared.js";

if (typeof window !== "undefined") {
  registerNativeSliderComponent();
}

export interface LxNativeSliderProps extends Omit<LxNativeNodeProps, "children"> {
  value?: number;
  min?: number;
  max?: number;
  step?: number;
  bufferedValue?: number;
  valueLabel?: "none" | "value" | "time";
  disabled?: boolean;
  tabIndex?: 0 | -1;
  onValueChange?: NativeHandler<ValuePayload>;
  onValueCommit?: NativeHandler<ValuePayload>;
  onFocus?: NativeHandler<FocusPayload>;
  onBlur?: NativeHandler<FocusPayload>;
  onPointerEnter?: NativeHandler<PointerPayload>;
  onPointerLeave?: NativeHandler<PointerPayload>;
}

export const LxNativeSlider = forwardRef<HTMLElement, LxNativeSliderProps>(
  (
    {
      id,
      automationId,
      className,
      style,
      pointerEvents,
      hidden,
      hiddenTransition,
      value,
      min,
      max,
      step,
      bufferedValue,
      valueLabel,
      disabled,
      tabIndex,
      onValueChange,
      onValueCommit,
      onFocus,
      onBlur,
      onPointerEnter,
      onPointerLeave,
      ...aria
    },
    ref
  ) => {
    const elementRef = useRef<HTMLElement | null>(null);
    const boundRef = useRef<HTMLElement | null>(null);
    const handlers = useRef({
      onValueChange,
      onValueCommit,
      onFocus,
      onBlur,
      onPointerEnter,
      onPointerLeave,
    });
    handlers.current = {
      onValueChange,
      onValueCommit,
      onFocus,
      onBlur,
      onPointerEnter,
      onPointerLeave,
    };
    const listeners = useRef({
      valuechange: payloadListener<ValuePayload>(() => handlers.current.onValueChange),
      valuecommit: payloadListener<ValuePayload>(() => handlers.current.onValueCommit),
      focus: payloadListener<FocusPayload>(() => handlers.current.onFocus),
      blur: payloadListener<FocusPayload>(() => handlers.current.onBlur),
      pointerenter: payloadListener<PointerPayload>(() => handlers.current.onPointerEnter),
      pointerleave: payloadListener<PointerPayload>(() => handlers.current.onPointerLeave),
    });

    const setRef = useCallback(
      (element: HTMLElement | null) => {
        boundRef.current = bindNativeEvents(boundRef.current, element, listeners.current);
        elementRef.current = element;
        assignNativeRef(ref, element);
      },
      [ref]
    );

    useEffect(
      () => () => {
        bindNativeEvents(boundRef.current, null, listeners.current);
        boundRef.current = null;
      },
      []
    );

    useEffect(() => {
      const el = elementRef.current;
      if (!el) return;
      setOptionalAttribute(el, "automation-id", automationId);
      setOptionalAttribute(el, "pointer-events", pointerEvents);
      setOptionalAttribute(el, "hidden-transition", hiddenTransition);
      setOptionalAttribute(el, "value", value);
      setOptionalAttribute(el, "min", min);
      setOptionalAttribute(el, "max", max);
      setOptionalAttribute(el, "step", step);
      setOptionalAttribute(el, "buffered-value", bufferedValue);
      setOptionalAttribute(el, "value-label", valueLabel);
      setOptionalAttribute(el, "disabled", disabled);
      setOptionalAttribute(el, "aria-label", aria["aria-label"]);
      if (typeof tabIndex === "number") {
        el.tabIndex = tabIndex;
      }
    }, [
      automationId,
      pointerEvents,
      hiddenTransition,
      value,
      min,
      max,
      step,
      bufferedValue,
      valueLabel,
      disabled,
      tabIndex,
      aria,
    ]);

    return React.createElement("lx-native-slider", {
      ref: setRef,
      id,
      className,
      style,
      hidden,
    });
  }
);

LxNativeSlider.displayName = "LxNativeSlider";

// packages/lingxia-vue/src/LxNativeSlider.vue
<script setup lang="ts">
import { onBeforeUnmount, ref, watch } from 'vue';
import {
  registerNativeSliderComponent,
  unwrapNativeEventPayload,
  type ValuePayload,
  type FocusPayload,
  type PointerPayload,
} from '@lingxia/elements';
import { bindElementEvents, unbindElementEvents } from './text_component_shared.js';

defineProps<{
  id?: string;
  automationId?: string;
  class?: string;
  value?: number;
  min?: number;
  max?: number;
  step?: number;
  bufferedValue?: number;
  valueLabel?: 'none' | 'value' | 'time';
  disabled?: boolean;
  pointerEvents?: 'auto' | 'none' | 'box-only' | 'box-none';
  hidden?: boolean;
  hiddenTransition?: 'none' | 'fade';
}>();

const emit = defineEmits<{
  valueChange: [payload: ValuePayload];
  valueCommit: [payload: ValuePayload];
  focus: [payload: FocusPayload];
  blur: [payload: FocusPayload];
  pointerEnter: [payload: PointerPayload];
  pointerLeave: [payload: PointerPayload];
}>();

if (typeof window !== 'undefined') {
  registerNativeSliderComponent();
}

const elementRef = ref<HTMLElement | null>(null);
let bound: HTMLElement | null = null;
const listeners: Record<string, EventListenerObject> = {
  valuechange: { handleEvent: (event) => emit('valueChange', unwrapNativeEventPayload(event)) },
  valuecommit: { handleEvent: (event) => emit('valueCommit', unwrapNativeEventPayload(event)) },
  focus: { handleEvent: (event) => emit('focus', unwrapNativeEventPayload(event)) },
  blur: { handleEvent: (event) => emit('blur', unwrapNativeEventPayload(event)) },
  pointerenter: { handleEvent: (event) => emit('pointerEnter', unwrapNativeEventPayload(event)) },
  pointerleave: { handleEvent: (event) => emit('pointerLeave', unwrapNativeEventPayload(event)) },
};

watch(elementRef, (element) => {
  bound = bindElementEvents(bound, element, listeners);
});
onBeforeUnmount(() => unbindElementEvents(bound, listeners));
</script>

<template>
  <lx-native-slider
    ref="elementRef"
    :id="id"
    :class="class"
    :automation-id="automationId"
    :value="value"
    :min="min"
    :max="max"
    :step="step"
    :buffered-value="bufferedValue"
    :value-label="valueLabel"
    :disabled="disabled"
    :pointer-events="pointerEvents"
    :hidden="hidden"
    :hidden-transition="hiddenTransition"
  />
</template>
