// packages/lingxia-react/src/LxVideo.tsx
import type { NativeStyle } from "./native/shared.js";
import React, { forwardRef, useCallback, useEffect, useId, useMemo, useRef } from 'react';
import {
  registerVideoComponent,
  unwrapNativeEventPayload,
  type LxVideoAttributes,
  type LxVideoEventHandlers,
  type LxVideoEventPayloads,
} from '@lingxia/elements';
import {
  buildVideoNativeAttrs,
  VIDEO_DOM_EVENT_MAP,
} from '@lingxia/elements';
import {
  assignForwardedRef,
  bindElementEvents,
  pickDomEventHandlers,
  unbindElementEvents,
} from './text_component_shared.js';

export interface LxVideoProps
  extends Omit<LxVideoAttributes, `on${string}` | "style">,
    LxVideoEventHandlers,
    Omit<React.HTMLAttributes<HTMLElement>,
      keyof LxVideoAttributes | keyof LxVideoEventHandlers | "children" | "dangerouslySetInnerHTML" | "ref" | "style"> {
  style?: NativeStyle;
}

if (typeof window !== "undefined") {
  registerVideoComponent();
}
export const LxVideo = forwardRef<HTMLElement, LxVideoProps>(({
  id,
  src,
  poster,
  objectFit,
  contentRotate,
  autoplay,
  loop,
  muted,
  controls,
  progressBar,
  live,
  volume,
  qualities,
  playbackRates,
  onPlayRequest,
  onPlay,
  onPlaying,
  onPause,
  onStop,
  onEnded,
  onTimeUpdate,
  onError,
  onLoadedMetadata,
  onFullscreenChange,
  onWaiting,
  onQualityChange,
  onRateChange,
  onVolumeChange,
  className,
  style,
  ...rest
}, ref) => {
  const elementRef = useRef<HTMLElement | null>(null);
  const boundElementRef = useRef<HTMLElement | null>(null);
  const reactId = useId();
  const resolvedId = useMemo(() => {
    if (id) return id;
    return `lx-video-${reactId.replace(/[:]/g, "")}`;
  }, [id, reactId]);
  const handlerRef = useRef<LxVideoEventHandlers>({
    onPlayRequest,
    onPlay,
    onPlaying,
    onPause,
    onStop,
    onEnded,
    onTimeUpdate,
    onError,
    onLoadedMetadata,
    onFullscreenChange,
    onWaiting,
    onQualityChange,
    onRateChange,
    onVolumeChange,
  });
  handlerRef.current = {
    onPlayRequest,
    onPlay,
    onPlaying,
    onPause,
    onStop,
    onEnded,
    onTimeUpdate,
    onError,
    onLoadedMetadata,
    onFullscreenChange,
    onWaiting,
    onQualityChange,
    onRateChange,
    onVolumeChange,
  };
  const listenerMapRef = useRef<Record<string, EventListenerObject>>(
    Object.fromEntries(
      Object.entries(VIDEO_DOM_EVENT_MAP).map(([propKey, eventName]) => [
        eventName,
        {
          handleEvent: (event: Event) => {
            const handler = handlerRef.current[propKey as keyof typeof handlerRef.current];
            if (typeof handler === "function") {
              (handler as (payload: LxVideoEventPayloads[keyof LxVideoEventPayloads]) => void)(unwrapNativeEventPayload(event));
            }
          },
        } satisfies EventListenerObject,
      ])
    )
  );
  const elementRefCallback = useCallback((element: HTMLElement | null) => {
    boundElementRef.current = bindElementEvents(boundElementRef.current, element, listenerMapRef.current);
    elementRef.current = element;
    assignForwardedRef(ref, element);
  }, [ref]);

  useEffect(() => () => {
    unbindElementEvents(boundElementRef.current, listenerMapRef.current);
    boundElementRef.current = null;
    elementRef.current = null;
  }, []);

  useEffect(() => {
    const el = elementRef.current;
    if (!el) return;
    if (contentRotate === undefined || contentRotate === null) {
      el.removeAttribute("content-rotate");
    } else {
      el.setAttribute("content-rotate", String(contentRotate).trim());
    }
    if (objectFit === undefined || objectFit === null) {
      el.removeAttribute("object-fit");
    } else {
      el.setAttribute("object-fit", String(objectFit).trim().toLowerCase());
    }
  }, [contentRotate, objectFit]);

  const domProps = buildVideoNativeAttrs({
    id: resolvedId,
    src,
    poster,
    autoplay,
    loop,
    muted,
    controls,
    progressBar,
    live,
    volume,
    qualities,
    playbackRates,
  }, rest as Record<string, unknown>);

  return React.createElement('lx-video', {
    ...pickDomEventHandlers(rest as Record<string, unknown>),
    ref: elementRefCallback,
    className,
    style,
    ...domProps
  });
});

LxVideo.displayName = 'LxVideo';

// packages/lingxia-vue/src/LxVideo.vue
<script setup lang="ts">
import { ref, computed, h, onBeforeUnmount, useAttrs, useId, watch } from 'vue';
import { registerVideoComponent, unwrapNativeEventPayload, type LxVideoEventPayloads } from '@lingxia/elements';
import {
  buildVideoNativeAttrs,
  VIDEO_DOM_EVENT_MAP,
} from '@lingxia/elements';
import { bindElementEvents, unbindElementEvents } from './text_component_shared.js';
import type { LxVideoProps } from './types.js';

const props = withDefaults(defineProps<LxVideoProps>(), {
  autoplay: false,
  loop: false,
  muted: false,
  controls: true,
  progressBar: true,
  live: false,
});
const attrs = useAttrs();

const emit = defineEmits<{
  playRequest: [payload: LxVideoEventPayloads["onPlayRequest"]];
  play: [payload: LxVideoEventPayloads["onPlay"]];
  playing: [payload: LxVideoEventPayloads["onPlaying"]];
  pause: [payload: LxVideoEventPayloads["onPause"]];
  stop: [payload: LxVideoEventPayloads["onStop"]];
  ended: [payload: LxVideoEventPayloads["onEnded"]];
  timeUpdate: [payload: LxVideoEventPayloads["onTimeUpdate"]];
  error: [payload: LxVideoEventPayloads["onError"]];
  loadedMetadata: [payload: LxVideoEventPayloads["onLoadedMetadata"]];
  fullscreenChange: [payload: LxVideoEventPayloads["onFullscreenChange"]];
  waiting: [payload: LxVideoEventPayloads["onWaiting"]];
  qualityChange: [payload: LxVideoEventPayloads["onQualityChange"]];
  rateChange: [payload: LxVideoEventPayloads["onRateChange"]];
  volumeChange: [payload: LxVideoEventPayloads["onVolumeChange"]];
}>();

if (typeof window !== 'undefined') {
  registerVideoComponent();
}

const elementRef = ref<HTMLElement | null>(null);
const vueId = useId();
let boundElement: HTMLElement | null = null;

const resolvedId = computed(() => props.id || `lx-video-${vueId.replace(/[:]/g, '')}`);

const videoEventListeners: Record<string, EventListenerObject> = {
  [VIDEO_DOM_EVENT_MAP.onPlayRequest]: { handleEvent: (event: Event) => emit('playRequest', unwrapNativeEventPayload(event)) },
  [VIDEO_DOM_EVENT_MAP.onPlay]: { handleEvent: (event: Event) => emit('play', unwrapNativeEventPayload(event)) },
  [VIDEO_DOM_EVENT_MAP.onPlaying]: { handleEvent: (event: Event) => emit('playing', unwrapNativeEventPayload(event)) },
  [VIDEO_DOM_EVENT_MAP.onPause]: { handleEvent: (event: Event) => emit('pause', unwrapNativeEventPayload(event)) },
  [VIDEO_DOM_EVENT_MAP.onStop]: { handleEvent: (event: Event) => emit('stop', unwrapNativeEventPayload(event)) },
  [VIDEO_DOM_EVENT_MAP.onEnded]: { handleEvent: (event: Event) => emit('ended', unwrapNativeEventPayload(event)) },
  [VIDEO_DOM_EVENT_MAP.onTimeUpdate]: { handleEvent: (event: Event) => emit('timeUpdate', unwrapNativeEventPayload(event)) },
  [VIDEO_DOM_EVENT_MAP.onError]: { handleEvent: (event: Event) => emit('error', unwrapNativeEventPayload(event)) },
  [VIDEO_DOM_EVENT_MAP.onLoadedMetadata]: { handleEvent: (event: Event) => emit('loadedMetadata', unwrapNativeEventPayload(event)) },
  [VIDEO_DOM_EVENT_MAP.onFullscreenChange]: { handleEvent: (event: Event) => emit('fullscreenChange', unwrapNativeEventPayload(event)) },
  [VIDEO_DOM_EVENT_MAP.onWaiting]: { handleEvent: (event: Event) => emit('waiting', unwrapNativeEventPayload(event)) },
  [VIDEO_DOM_EVENT_MAP.onQualityChange]: { handleEvent: (event: Event) => emit('qualityChange', unwrapNativeEventPayload(event)) },
  [VIDEO_DOM_EVENT_MAP.onVolumeChange]: { handleEvent: (event: Event) => emit('volumeChange', unwrapNativeEventPayload(event)) },
  [VIDEO_DOM_EVENT_MAP.onRateChange]: { handleEvent: (event: Event) => emit('rateChange', unwrapNativeEventPayload(event)) },
};

watch(elementRef, (element) => {
  boundElement = bindElementEvents(boundElement, element, videoEventListeners);
});

onBeforeUnmount(() => {
  unbindElementEvents(boundElement, videoEventListeners);
});

watch(
  [elementRef, () => props.contentRotate, () => props.objectFit],
  () => {
    const el = elementRef.value;
    if (!el) return;
    const contentRotate = props.contentRotate;
    if (contentRotate === undefined || contentRotate === null || contentRotate === '') {
      el.removeAttribute('content-rotate');
    } else {
      el.setAttribute('content-rotate', String(contentRotate).trim());
    }
    const objectFit = props.objectFit;
    if (objectFit === undefined || objectFit === null || objectFit === '') {
      el.removeAttribute('object-fit');
    } else {
      el.setAttribute('object-fit', String(objectFit).trim().toLowerCase());
    }
  },
  { immediate: true }
);

const domProps = computed(() => {
  const result = buildVideoNativeAttrs({
    ...props,
    id: resolvedId.value,
  }, attrs as Record<string, unknown>);
  return {
    ...result,
    class: props.class ?? attrs.class,
    style: props.style ?? attrs.style,
  };
});

defineExpose({ el: elementRef });

const render = () => h('lx-video', { ref: elementRef, ...domProps.value });
</script>

<template>
  <render />
</template>
