// tools/lingxia-cli/templates/lxapp-create/native/pages/home/index.vue
<script setup lang="ts">
import '../../app.css';
import { native } from '@lingxia/native';
</script>

<template>
  <main class="page">
    <section class="card">
      <h1 data-testid="home-title">Hello, LingXia</h1>
      <p>Rust native APIs are available from the generated <code>native</code> module.</p>
    </section>
  </main>
</template>

// tools/lingxia-cli/templates/lxapp-create/native/pages/home/index.tsx
import React from 'react';
import '../../app.css';
import { native } from '@lingxia/native';

export default function HomePage() {
  return (
    <main className="page">
      <section className="card">
        <h1 data-testid="home-title">Hello, LingXia</h1>
        <p>Rust native APIs are available from the generated <code>native</code> module.</p>
      </section>
    </main>
  );
}
