// examples/lingxia-showcase/lxapp/pages/todo/index.tsx
import React from 'react';
import { useLxPage } from '@lingxia/react';
import '../../tailwind.css';
import './index.css';

import type { TodoFilter, TodoPage as TodoContract } from './contract';

export default function TodoPage() {
  const { data, actions } = useLxPage<TodoContract['data'], TodoContract['actions']>();
  const {
    addTodo,
    toggleTodo,
    deleteTodo,
    clearCompleted,
    setFilter,
  } = actions;
  const todos = data?.todos ?? [];
  const currentFilter = data?.currentFilter ?? 'all';

  const [newTodo, setNewTodo] = React.useState('');

  const filteredTodos = React.useMemo(() => {
    switch (currentFilter) {
      case 'active':
        return todos.filter(todo => !todo.completed);
      case 'completed':
        return todos.filter(todo => todo.completed);
      default:
        return todos;
    }
  }, [todos, currentFilter]);

  const todoStats = React.useMemo(() => {
    const completedCount = todos.filter(todo => todo.completed).length;
    return {
      total: todos.length,
      completed: completedCount,
      active: todos.length - completedCount,
    };
  }, [todos]);

  const handleAddTodo = React.useCallback(() => {
    const text = newTodo.trim();
    if (!text) {
      return;
    }
    addTodo({ text });
    setNewTodo('');
  }, [newTodo, addTodo]);

  const handleKeyDown = (event: React.KeyboardEvent<HTMLInputElement>) => {
    if (event.key === 'Enter') {
      handleAddTodo();
    }
  };

  const handleToggleAll = React.useCallback(() => {
    const allCompleted = todoStats.active === 0;
    todos.forEach(todo => {
      if (todo.completed !== !allCompleted) {
        toggleTodo({ id: todo.id });
      }
    });
  }, [todos, todoStats.active, toggleTodo]);

  const handleFilterClick = (filter: TodoFilter) => (
    event: React.MouseEvent<HTMLAnchorElement>
  ) => {
    event.preventDefault();
    setFilter({ filter });
  };

  const hasTodos = todos.length > 0;

  return (
    <div className="todo-page" data-testid="todo-page">
      <section className="todoapp">
        <h1>todos</h1>
      <input
        className="new-todo"
        data-testid="todo-input"
        data-controlled-value={newTodo}
        placeholder="What needs to be done?"
        value={newTodo}
        onChange={event => setNewTodo(event.target.value)}
        onKeyDown={handleKeyDown}
        autoFocus
      />

      {!hasTodos && (
        <div className="empty-state">
          <div className="empty-state-icon">📝</div>
          <div className="empty-state-text">No tasks yet</div>
          <div className="empty-state-hint">Add a task above to get started</div>
        </div>
      )}

      {hasTodos && (
        <div className="main">
          <input
            id="toggle-all"
            className="toggle-all"
            type="checkbox"
            checked={todoStats.active === 0 && todos.length > 0}
            onChange={handleToggleAll}
          />
          <label htmlFor="toggle-all">Mark all as complete</label>
          <ul className="todo-list">
            {filteredTodos.map(todo => (
              <li
                key={todo.id}
                className={todo.completed ? 'completed' : ''}
                data-testid="todo-item"
              >
                <div className="view">
                  <input
                    id={`todo-${todo.id}`}
                    className="toggle"
                    data-testid="todo-toggle"
                    type="checkbox"
                    checked={todo.completed}
                    onChange={() => toggleTodo({ id: todo.id })}
                  />
                  <label htmlFor={`todo-${todo.id}`} data-testid="todo-label">{todo.text}</label>
                  <button
                    className="destroy"
                    data-testid="todo-delete"
                    onClick={() => deleteTodo({ id: todo.id })}
                    aria-label="Delete todo"
                  />
                </div>
              </li>
            ))}
          </ul>
        </div>
      )}

      {hasTodos && (
        <footer className="footer">
          <span className="todo-count">
            <strong>{todoStats.active}</strong>{' '}
            {todoStats.active === 1 ? 'item' : 'items'} left
          </span>
          <ul className="filters">
            <li>
              <a
                href="#/"
                data-testid="todo-filter-all"
                className={currentFilter === 'all' ? 'selected' : ''}
                onClick={handleFilterClick('all')}
              >
                All
              </a>
            </li>
            <li>
              <a
                href="#/active"
                data-testid="todo-filter-active"
                className={currentFilter === 'active' ? 'selected' : ''}
                onClick={handleFilterClick('active')}
              >
                Active
              </a>
            </li>
            <li>
              <a
                href="#/completed"
                data-testid="todo-filter-completed"
                className={currentFilter === 'completed' ? 'selected' : ''}
                onClick={handleFilterClick('completed')}
              >
                Completed
              </a>
            </li>
          </ul>
          {todoStats.completed > 0 && (
            <button className="clear-completed" data-testid="todo-clear-completed" onClick={clearCompleted}>
              Clear completed
            </button>
          )}
        </footer>
      )}
      </section>
    </div>
  );
}

// examples/lingxia-showcase/lxapp/pages/todo/index.vue
<template>
  <div class="todo-page" data-testid="todo-page">
    <section class="todoapp">
      <h1>todos</h1>
      <input
        class="new-todo"
        data-testid="todo-input"
        :data-controlled-value="newTodo"
        placeholder="What needs to be done?"
        v-model="newTodo"
        @keydown.enter="handleAddTodo"
        autofocus
      />

      <div v-if="!hasTodos" class="empty-state">
        <div class="empty-state-icon">📝</div>
        <div class="empty-state-text">No tasks yet</div>
        <div class="empty-state-hint">Add a task above to get started</div>
      </div>

      <div v-if="hasTodos" class="main">
        <input
          id="toggle-all"
          class="toggle-all"
          type="checkbox"
          :checked="todoStats.active === 0 && todos.length > 0"
          @change="handleToggleAll"
        />
        <label for="toggle-all">Mark all as complete</label>
        <ul class="todo-list">
          <li
            v-for="todo in filteredTodos"
            :key="todo.id"
            :class="{ completed: todo.completed }"
            data-testid="todo-item"
          >
            <div class="view">
              <input
                :id="`todo-${todo.id}`"
                class="toggle"
                data-testid="todo-toggle"
                type="checkbox"
                :checked="todo.completed"
                @change="toggleTodo({ id: todo.id })"
              />
              <label :for="`todo-${todo.id}`" data-testid="todo-label">{{ todo.text }}</label>
              <button
                class="destroy"
                data-testid="todo-delete"
                @click="deleteTodo({ id: todo.id })"
                aria-label="Delete todo"
              />
            </div>
          </li>
        </ul>
      </div>

      <footer v-if="hasTodos" class="footer">
        <span class="todo-count">
          <strong>{{ todoStats.active }}</strong>
          {{ todoStats.active === 1 ? 'item' : 'items' }} left
        </span>
        <ul class="filters">
          <li>
            <a
              href="#/"
              data-testid="todo-filter-all"
              :class="{ selected: currentFilter === 'all' }"
              @click.prevent="setFilter({ filter: 'all' })"
            >
              All
            </a>
          </li>
          <li>
            <a
              href="#/active"
              data-testid="todo-filter-active"
              :class="{ selected: currentFilter === 'active' }"
              @click.prevent="setFilter({ filter: 'active' })"
            >
              Active
            </a>
          </li>
          <li>
            <a
              href="#/completed"
              data-testid="todo-filter-completed"
              :class="{ selected: currentFilter === 'completed' }"
              @click.prevent="setFilter({ filter: 'completed' })"
            >
              Completed
            </a>
          </li>
        </ul>
        <button v-if="todoStats.completed > 0" class="clear-completed" data-testid="todo-clear-completed" @click="clearCompleted">
          Clear completed
        </button>
      </footer>
    </section>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import { useLxPage } from '@lingxia/vue';
import '../../tailwind.css';
import './index.css';

import type { TodoFilter, TodoPage as TodoContract } from './contract';

const { data, actions } = useLxPage<TodoContract['data'], TodoContract['actions']>();
const {
  addTodo,
  toggleTodo,
  deleteTodo,
  clearCompleted,
  setFilter,
} = actions;

const newTodo = ref('');

const todos = computed(() => data?.todos ?? []);
const currentFilter = computed(() => data?.currentFilter ?? 'all');

const filteredTodos = computed(() => {
  switch (currentFilter.value) {
    case 'active':
      return todos.value.filter(todo => !todo.completed);
    case 'completed':
      return todos.value.filter(todo => todo.completed);
    default:
      return todos.value;
  }
});

const todoStats = computed(() => {
  const completedCount = todos.value.filter(todo => todo.completed).length;
  return {
    total: todos.value.length,
    completed: completedCount,
    active: todos.value.length - completedCount,
  };
});

const hasTodos = computed(() => todos.value.length > 0);

function handleAddTodo() {
  const text = newTodo.value.trim();
  if (!text) return;
  addTodo({ text });
  newTodo.value = '';
}

function handleToggleAll() {
  const allCompleted = todoStats.value.active === 0;
  todos.value.forEach(todo => {
    if (todo.completed !== !allCompleted) {
      toggleTodo({ id: todo.id });
    }
  });
}
</script>
