// packages/lingxia-vue/src/LxNativeCover.vue
<script setup lang="ts">
import { registerNativeCoverComponent } from '@lingxia/elements';

defineProps<{
  id?: string;
  automationId?: string;
  class?: string;
  pointerEvents?: 'auto' | 'none' | 'box-only' | 'box-none';
  hidden?: boolean;
  hiddenTransition?: 'none' | 'fade';
  scrim?: 'none' | 'top' | 'bottom' | 'full';
  scrimOpacity?: number;
  role?: 'group' | 'region' | 'status' | 'presentation' | 'none';
}>();

if (typeof window !== 'undefined') {
  registerNativeCoverComponent();
}
</script>

<template>
  <lx-native-cover
    :id="id"
    :class="class"
    :automation-id="automationId"
    :pointer-events="pointerEvents"
    :hidden="hidden"
    :hidden-transition="hiddenTransition"
    :scrim="scrim"
    :scrim-opacity="scrimOpacity"
    :role="role"
  >
    <slot />
  </lx-native-cover>
</template>

// packages/lingxia-react/src/native/LxNativeCover.tsx
import React, { forwardRef, useCallback, useEffect, useRef } from "react";
import { registerNativeCoverComponent } from "@lingxia/elements";
import {
  assignNativeRef,
  setOptionalAttribute,
  type LxNativeNodeProps,
} from "./shared.js";

if (typeof window !== "undefined") {
  registerNativeCoverComponent();
}

export interface LxNativeCoverProps extends LxNativeNodeProps {
  scrim?: "none" | "top" | "bottom" | "full";
  scrimOpacity?: number;
  role?: "group" | "region" | "status" | "presentation" | "none";
}

export const LxNativeCover = forwardRef<HTMLElement, LxNativeCoverProps>(
  (
    {
      id,
      automationId,
      className,
      style,
      pointerEvents,
      hidden,
      hiddenTransition,
      scrim,
      scrimOpacity,
      role,
      children,
      ...aria
    },
    ref
  ) => {
    const elementRef = useRef<HTMLElement | null>(null);
    const setRef = useCallback(
      (element: HTMLElement | null) => {
        elementRef.current = element;
        assignNativeRef(ref, element);
      },
      [ref]
    );

    useEffect(() => {
      const el = elementRef.current;
      if (!el) return;
      setOptionalAttribute(el, "automation-id", automationId);
      setOptionalAttribute(el, "pointer-events", pointerEvents);
      setOptionalAttribute(el, "hidden-transition", hiddenTransition);
      setOptionalAttribute(el, "scrim", scrim);
      setOptionalAttribute(el, "scrim-opacity", scrimOpacity);
      setOptionalAttribute(el, "role", role);
      setOptionalAttribute(el, "aria-label", aria["aria-label"]);
    }, [automationId, pointerEvents, hiddenTransition, scrim, scrimOpacity, role, aria]);

    return React.createElement(
      "lx-native-cover",
      { ref: setRef, id, className, style, hidden },
      children
    );
  }
);

LxNativeCover.displayName = "LxNativeCover";
