// packages/lingxia-vue/src/LxNativeText.vue
<script setup lang="ts">
import { registerNativeTextComponent } from '@lingxia/elements';

defineProps<{
  id?: string;
  automationId?: string;
  class?: string;
  pointerEvents?: 'auto' | 'none' | 'box-only' | 'box-none';
  hidden?: boolean;
  hiddenTransition?: 'none' | 'fade';
  maxLines?: number;
  dir?: 'ltr' | 'rtl' | 'auto';
  fontSize?: number | string;
  fontWeight?: number | string;
  lineHeight?: number | string;
  textAlign?: 'start' | 'center' | 'end';
  color?: string;
}>();

if (typeof window !== 'undefined') {
  registerNativeTextComponent();
}
</script>

<template>
  <lx-native-text
    :id="id"
    :class="class"
    :automation-id="automationId"
    :pointer-events="pointerEvents"
    :hidden="hidden"
    :hidden-transition="hiddenTransition"
    :max-lines="maxLines"
    :dir="dir"
    :font-size="fontSize"
    :font-weight="fontWeight"
    :line-height="lineHeight"
    :text-align="textAlign"
    :color="color"
  >
    <slot />
  </lx-native-text>
</template>

// packages/lingxia-react/src/native/LxNativeText.tsx
import React, { forwardRef, useCallback, useEffect, useRef } from "react";
import { registerNativeTextComponent } from "@lingxia/elements";
import {
  assignNativeRef,
  setOptionalAttribute,
  type LxNativeNodeProps,
} from "./shared.js";

if (typeof window !== "undefined") {
  registerNativeTextComponent();
}

export interface LxNativeTextProps extends Omit<LxNativeNodeProps, "children"> {
  maxLines?: number;
  dir?: "ltr" | "rtl" | "auto";
  fontSize?: number | string;
  fontWeight?: number | string;
  lineHeight?: number | string;
  textAlign?: "start" | "center" | "end";
  color?: string;
  children?: string | number;
}

export const LxNativeText = forwardRef<HTMLElement, LxNativeTextProps>(
  (
    {
      id,
      automationId,
      className,
      style,
      pointerEvents,
      hidden,
      hiddenTransition,
      maxLines,
      dir,
      fontSize,
      fontWeight,
      lineHeight,
      textAlign,
      color,
      children,
      ...aria
    },
    ref
  ) => {
    const elementRef = useRef<HTMLElement | null>(null);
    const setRef = useCallback(
      (element: HTMLElement | null) => {
        elementRef.current = element;
        assignNativeRef(ref, element);
      },
      [ref]
    );

    useEffect(() => {
      const el = elementRef.current;
      if (!el) return;
      setOptionalAttribute(el, "automation-id", automationId);
      setOptionalAttribute(el, "pointer-events", pointerEvents);
      setOptionalAttribute(el, "hidden-transition", hiddenTransition);
      setOptionalAttribute(el, "max-lines", maxLines);
      setOptionalAttribute(el, "dir", dir);
      setOptionalAttribute(el, "font-size", fontSize);
      setOptionalAttribute(el, "font-weight", fontWeight);
      setOptionalAttribute(el, "line-height", lineHeight);
      setOptionalAttribute(el, "text-align", textAlign);
      setOptionalAttribute(el, "color", color);
      setOptionalAttribute(el, "aria-label", aria["aria-label"]);
    }, [
      automationId,
      pointerEvents,
      hiddenTransition,
      maxLines,
      dir,
      fontSize,
      fontWeight,
      lineHeight,
      textAlign,
      color,
      aria,
    ]);

    return React.createElement(
      "lx-native-text",
      { ref: setRef, id, className, style, hidden },
      children
    );
  }
);

LxNativeText.displayName = "LxNativeText";
