// examples/lingxia-showcase/lxapp/pages/components/index.tsx
import React from 'react';
import { useLxPage } from '@lingxia/react';
import '../../tailwind.css';

export default function ComponentsPage() {
  const { actions } = useLxPage();
  const { navigateTo } = actions;

  return (
    <div className="min-h-screen bg-surface-100" data-testid="components-page">
      <div className="px-3 py-2 pb-12 space-y-2">

        {/* Compact Header */}
        <div className="bg-linear-to-r from-blue-500 to-purple-600 rounded-xl shadow-sm px-4 py-3 flex items-center gap-3">
          <div className="w-10 h-10 bg-surface/20 rounded-lg flex items-center justify-center">
            <svg viewBox="0 0 24 24" fill="none" stroke="white" strokeWidth="2" className="w-5 h-5">
              <rect x="3" y="3" width="7" height="7" rx="1" />
              <rect x="14" y="3" width="7" height="7" rx="1" />
              <rect x="14" y="14" width="7" height="7" rx="1" />
              <rect x="3" y="14" width="7" height="7" rx="1" />
            </svg>
          </div>
          <div>
            <div className="text-base text-white font-semibold">Component Gallery</div>
            <div className="text-xs text-white/70">Native-backed UI components</div>
          </div>
        </div>

        {/* Component List */}
        <div className="bg-surface rounded-xl shadow-sm border border-line-200 overflow-hidden divide-y divide-line-100">
          {/* Video */}
          <div
            data-testid="components-video"
            className="px-4 py-3.5 hover:bg-surface-50 cursor-pointer flex items-center justify-between group transition-colors"
            onClick={() => navigateTo({ page: 'video' })}
          >
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 bg-linear-to-br from-blue-500 to-cyan-500 rounded-lg flex items-center justify-center">
                <svg viewBox="0 0 24 24" fill="white" className="w-5 h-5">
                  <polygon points="5 3 19 12 5 21 5 3" />
                </svg>
              </div>
              <div>
                <div className="text-sm font-medium text-gray-900">Video Player</div>
                <div className="text-xs text-gray-500">Native video with controls</div>
              </div>
            </div>
            <div className="w-5 h-5 text-gray-400 group-hover:text-blue-500 dark:group-hover:text-blue-400 transition-colors">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M9 18l6-6-6-6" />
              </svg>
            </div>
          </div>

          {/* Media Swiper */}
          <div
            data-testid="components-swiper"
            className="px-4 py-3.5 hover:bg-surface-50 cursor-pointer flex items-center justify-between group transition-colors"
            onClick={() => navigateTo({ page: 'swiper' })}
          >
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 bg-linear-to-br from-orange-500 to-rose-500 rounded-lg flex items-center justify-center">
                <svg viewBox="0 0 24 24" fill="none" stroke="white" strokeWidth="2" className="w-5 h-5">
                  <rect x="3" y="5" width="18" height="14" rx="2" />
                  <circle cx="9" cy="11" r="1.5" fill="white" />
                  <path d="M21 15l-5-5-9 9" />
                </svg>
              </div>
              <div>
                <div className="text-sm font-medium text-gray-900">Media Swiper</div>
                <div className="text-xs text-gray-500">Image/video carousel via chooseMedia</div>
              </div>
            </div>
            <div className="w-5 h-5 text-gray-400 group-hover:text-rose-500 dark:group-hover:text-rose-400 transition-colors">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M9 18l6-6-6-6" />
              </svg>
            </div>
          </div>

          {/* Navigator */}
          <div
            data-testid="components-navigator"
            className="px-4 py-3.5 hover:bg-surface-50 cursor-pointer flex items-center justify-between group transition-colors"
            onClick={() => navigateTo({ page: 'navigator' })}
          >
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 bg-linear-to-br from-emerald-500 to-teal-500 rounded-lg flex items-center justify-center">
                <svg viewBox="0 0 24 24" fill="none" stroke="white" strokeWidth="2" className="w-5 h-5">
                  <path d="M12 3l7 18-7-4-7 4 7-18z" />
                </svg>
              </div>
              <div>
                <div className="text-sm font-medium text-gray-900">Navigator</div>
                <div className="text-xs text-gray-500">Navigate pages and apps</div>
              </div>
            </div>
            <div className="w-5 h-5 text-gray-400 group-hover:text-emerald-500 dark:group-hover:text-emerald-400 transition-colors">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M9 18l6-6-6-6" />
              </svg>
            </div>
          </div>

          {/* Picker */}
          <div
            data-testid="components-picker"
            className="px-4 py-3.5 hover:bg-surface-50 cursor-pointer flex items-center justify-between group transition-colors"
            onClick={() => navigateTo({ page: 'picker' })}
          >
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 bg-linear-to-br from-purple-500 to-pink-500 rounded-lg flex items-center justify-center">
                <svg viewBox="0 0 24 24" fill="none" stroke="white" strokeWidth="2" className="w-5 h-5">
                  <rect x="4" y="6" width="16" height="12" rx="2" />
                  <line x1="12" y1="6" x2="12" y2="18" />
                </svg>
              </div>
              <div>
                <div className="text-sm font-medium text-gray-900">Picker</div>
                <div className="text-xs text-gray-500">Native picker with value/onChange</div>
              </div>
            </div>
            <div className="w-5 h-5 text-gray-400 group-hover:text-purple-500 dark:group-hover:text-purple-400 transition-colors">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M9 18l6-6-6-6" />
              </svg>
            </div>
          </div>


        </div>

      </div>
    </div>
  );
}

// examples/lingxia-showcase/lxapp/pages/components/index.vue
<template>
  <div class="min-h-screen bg-surface-100" data-testid="components-page">
    <div class="px-3 py-2 pb-12 space-y-2">

      <!-- Compact Header -->
      <div class="bg-linear-to-r from-blue-500 to-purple-600 rounded-xl shadow-sm px-4 py-3 flex items-center gap-3">
        <div class="w-10 h-10 bg-surface/20 rounded-lg flex items-center justify-center">
          <svg viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="2" class="w-5 h-5">
            <rect x="3" y="3" width="7" height="7" rx="1" />
            <rect x="14" y="3" width="7" height="7" rx="1" />
            <rect x="14" y="14" width="7" height="7" rx="1" />
            <rect x="3" y="14" width="7" height="7" rx="1" />
          </svg>
        </div>
        <div>
          <div class="text-base text-white font-semibold">Component Gallery</div>
          <div class="text-xs text-white/70">Native-backed UI components</div>
        </div>
      </div>

      <!-- Component List -->
      <div class="bg-surface rounded-xl shadow-sm border border-line-200 overflow-hidden divide-y divide-line-100">
        <!-- Video -->
        <div
          data-testid="components-video"
          class="px-4 py-3.5 hover:bg-surface-50 cursor-pointer flex items-center justify-between group transition-colors"
          @click="navigateTo({ page: 'video' })"
        >
          <div class="flex items-center gap-3">
            <div class="w-10 h-10 bg-linear-to-br from-blue-500 to-cyan-500 rounded-lg flex items-center justify-center">
              <svg viewBox="0 0 24 24" fill="white" class="w-5 h-5">
                <polygon points="5 3 19 12 5 21 5 3" />
              </svg>
            </div>
            <div>
              <div class="text-sm font-medium text-gray-900">Video Player</div>
              <div class="text-xs text-gray-500">Native video with controls</div>
            </div>
          </div>
          <div class="w-5 h-5 text-gray-400 group-hover:text-blue-500 dark:group-hover:text-blue-400 transition-colors">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <path d="M9 18l6-6-6-6" />
            </svg>
          </div>
        </div>

        <!-- Media Swiper -->
        <div
          data-testid="components-swiper"
          class="px-4 py-3.5 hover:bg-surface-50 cursor-pointer flex items-center justify-between group transition-colors"
          @click="navigateTo({ page: 'swiper' })"
        >
          <div class="flex items-center gap-3">
            <div class="w-10 h-10 bg-linear-to-br from-orange-500 to-rose-500 rounded-lg flex items-center justify-center">
              <svg viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="2" class="w-5 h-5">
                <rect x="3" y="5" width="18" height="14" rx="2" />
                <circle cx="9" cy="11" r="1.5" fill="white" />
                <path d="M21 15l-5-5-9 9" />
              </svg>
            </div>
            <div>
              <div class="text-sm font-medium text-gray-900">Media Swiper</div>
              <div class="text-xs text-gray-500">Image/video carousel via chooseMedia</div>
            </div>
          </div>
          <div class="w-5 h-5 text-gray-400 group-hover:text-rose-500 dark:group-hover:text-rose-400 transition-colors">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <path d="M9 18l6-6-6-6" />
            </svg>
          </div>
        </div>

        <!-- Navigator -->
        <div
          data-testid="components-navigator"
          class="px-4 py-3.5 hover:bg-surface-50 cursor-pointer flex items-center justify-between group transition-colors"
          @click="navigateTo({ page: 'navigator' })"
        >
          <div class="flex items-center gap-3">
            <div class="w-10 h-10 bg-linear-to-br from-emerald-500 to-teal-500 rounded-lg flex items-center justify-center">
              <svg viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="2" class="w-5 h-5">
                <path d="M12 3l7 18-7-4-7 4 7-18z" />
              </svg>
            </div>
            <div>
              <div class="text-sm font-medium text-gray-900">Navigator</div>
              <div class="text-xs text-gray-500">Navigate pages and apps</div>
            </div>
          </div>
          <div class="w-5 h-5 text-gray-400 group-hover:text-emerald-500 dark:group-hover:text-emerald-400 transition-colors">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <path d="M9 18l6-6-6-6" />
            </svg>
          </div>
        </div>

        <!-- Picker -->
        <div
          data-testid="components-picker"
          class="px-4 py-3.5 hover:bg-surface-50 cursor-pointer flex items-center justify-between group transition-colors"
          @click="navigateTo({ page: 'picker' })"
        >
          <div class="flex items-center gap-3">
            <div class="w-10 h-10 bg-linear-to-br from-purple-500 to-pink-500 rounded-lg flex items-center justify-center">
              <svg viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="2" class="w-5 h-5">
                <rect x="4" y="6" width="16" height="12" rx="2" />
                <line x1="12" y1="6" x2="12" y2="18" />
              </svg>
            </div>
            <div>
              <div class="text-sm font-medium text-gray-900">Picker</div>
              <div class="text-xs text-gray-500">Native picker with value/onChange</div>
            </div>
          </div>
          <div class="w-5 h-5 text-gray-400 group-hover:text-purple-500 dark:group-hover:text-purple-400 transition-colors">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <path d="M9 18l6-6-6-6" />
            </svg>
          </div>
        </div>


      </div>

    </div>
  </div>
</template>

<script setup lang="ts">
import '../../tailwind.css';
import { useLxPage } from '@lingxia/vue';

type PageActions = {
  navigateTo(payload: { page: string; query?: Record<string, string> }): void;
};

const { actions } = useLxPage();
const { navigateTo } = actions;
</script>
