// packages/lingxia-components/src/vue/LxInput.vue
<script setup lang="ts">
import { computed, h, onBeforeUnmount, ref, useAttrs, watch } from 'vue';
import { registerInputComponent } from '../input.js';
import { buildInputNativeAttrs } from '../text_component_native_attrs.js';
import type { LxInputProps } from './types.js';
import {
  bindElementEvents,
  getCustomEventDetail,
  unbindElementEvents,
} from './text_component_shared.js';

const props = withDefaults(defineProps<LxInputProps>(), {
  type: 'text',
  disabled: false,
  confirmType: 'done',
});
const attrs = useAttrs();

const emit = defineEmits<{
  'update:modelValue': [value: string];
  input: [detail: Record<string, unknown>];
  change: [detail: Record<string, unknown>];
  focus: [detail: Record<string, unknown>];
  blur: [detail: Record<string, unknown>];
  confirm: [detail: Record<string, unknown>];
  keyboardHeightChange: [detail: Record<string, unknown>];
  nicknameReview: [detail: Record<string, unknown>];
}>();

if (typeof window !== 'undefined') {
  registerInputComponent();
}

const elementRef = ref<HTMLElement | null>(null);
let boundElement: HTMLElement | null = null;

const inputEventListeners: Record<string, EventListenerObject> = {
  input: {
    handleEvent: (event: Event) => {
      const detail = getCustomEventDetail<Record<string, unknown>>(event);
      if (typeof detail.value === 'string') {
        emit('update:modelValue', detail.value);
      }
      emit('input', detail);
    },
  },
  change: {
    handleEvent: (event: Event) => emit('change', getCustomEventDetail<Record<string, unknown>>(event)),
  },
  focus: {
    handleEvent: (event: Event) => emit('focus', getCustomEventDetail<Record<string, unknown>>(event)),
  },
  blur: {
    handleEvent: (event: Event) => emit('blur', getCustomEventDetail<Record<string, unknown>>(event)),
  },
  confirm: {
    handleEvent: (event: Event) => emit('confirm', getCustomEventDetail<Record<string, unknown>>(event)),
  },
  keyboardheightchange: {
    handleEvent: (event: Event) => emit('keyboardHeightChange', getCustomEventDetail<Record<string, unknown>>(event)),
  },
  nicknamereview: {
    handleEvent: (event: Event) => emit('nicknameReview', getCustomEventDetail<Record<string, unknown>>(event)),
  },
};

watch(elementRef, (element) => {
  boundElement = bindElementEvents(boundElement, element, inputEventListeners);
});

onBeforeUnmount(() => {
  unbindElementEvents(boundElement, inputEventListeners);
});

const inputProps = computed<Record<string, unknown>>(() => {
  const result: Record<string, unknown> = buildInputNativeAttrs({
    ...props,
    id: props.id ?? (typeof attrs.id === 'string' ? attrs.id : undefined),
  }, attrs as Record<string, unknown>, elementRef.value !== null);
  result.class = props.class ?? attrs.class;
  result.style = props.style ?? attrs.style;
  return result;
});

defineExpose({ el: elementRef });

const renderInput = () => h('lx-input', { ref: elementRef, ...inputProps.value });
</script>

<template>
  <renderInput />
</template>

// packages/lingxia-react/src/LxInput.tsx
import React, { forwardRef, useCallback, useEffect, useRef } from "react";
import { registerInputComponent } from "@lingxia/elements";
import { buildInputNativeAttrs } from "@lingxia/elements";
import {
  assignForwardedRef,
  bindElementEvents,
  getCustomEventDetail,
  unbindElementEvents,
} from "./text_component_shared.js";

export interface LxInputEventDetail {
  value?: string;
  cursor?: number;
  keyCode?: number;
  height?: number;
  duration?: number;
  encryptedValue?: string;
  encryptError?: string;
  pass?: boolean;
  timeout?: boolean;
}

export interface LxInputProps {
  id?: string;
  value?: string;
  defaultValue?: string;
  type?: "text" | "number" | "password" | "digit";
  password?: boolean;
  placeholder?: string;
  placeholderStyle?: string;
  placeholderClass?: string;
  maxlength?: number;
  cursorSpacing?: number;
  autoFocus?: boolean;
  disabled?: boolean;
  focus?: boolean;
  confirmType?: "send" | "search" | "next" | "go" | "done";
  alwaysEmbed?: boolean;
  confirmHold?: boolean;
  cursor?: number;
  cursorColor?: string;
  selectionStart?: number;
  selectionEnd?: number;
  adjustPosition?: boolean;
  holdKeyboard?: boolean;

  onInput?: (detail: LxInputEventDetail) => void;
  onChange?: (detail: LxInputEventDetail) => void;
  onFocus?: (detail: LxInputEventDetail) => void;
  onBlur?: (detail: LxInputEventDetail) => void;
  onConfirm?: (detail: LxInputEventDetail) => void;
  onKeyboardHeightChange?: (detail: LxInputEventDetail) => void;
  onNicknameReview?: (detail: LxInputEventDetail) => void;

  // Logic bindings (CLI-generated)
  pageBindings?: Record<string, string>;

  className?: string;
  style?: React.CSSProperties;
}

if (typeof window !== "undefined") {
  registerInputComponent();
}

export const LxInput = forwardRef<HTMLElement, LxInputProps>(({
  value,
  defaultValue,
  type,
  password,
  placeholder,
  placeholderStyle,
  placeholderClass,
  maxlength,
  cursorSpacing,
  autoFocus,
  disabled,
  focus,
  confirmType,
  alwaysEmbed,
  confirmHold,
  cursor,
  cursorColor,
  selectionStart,
  selectionEnd,
  adjustPosition,
  holdKeyboard,
  onInput,
  onChange,
  onFocus,
  onBlur,
  onConfirm,
  onKeyboardHeightChange,
  onNicknameReview,
  pageBindings,
  className,
  style,
  id,
  ...rest
}, ref) => {
  const elementRef = useRef<HTMLElement | null>(null);
  const boundElementRef = useRef<HTMLElement | null>(null);
  const handlerRef = useRef({
    onInput,
    onChange,
    onFocus,
    onBlur,
    onConfirm,
    onKeyboardHeightChange,
    onNicknameReview,
  });
  handlerRef.current = {
    onInput,
    onChange,
    onFocus,
    onBlur,
    onConfirm,
    onKeyboardHeightChange,
    onNicknameReview,
  };
  const listenerMapRef = useRef<Record<string, EventListenerObject>>({
    input: {
      handleEvent: (event: Event) => handlerRef.current.onInput?.(getCustomEventDetail<LxInputEventDetail>(event)),
    },
    change: {
      handleEvent: (event: Event) => handlerRef.current.onChange?.(getCustomEventDetail<LxInputEventDetail>(event)),
    },
    focus: {
      handleEvent: (event: Event) => handlerRef.current.onFocus?.(getCustomEventDetail<LxInputEventDetail>(event)),
    },
    blur: {
      handleEvent: (event: Event) => handlerRef.current.onBlur?.(getCustomEventDetail<LxInputEventDetail>(event)),
    },
    confirm: {
      handleEvent: (event: Event) => handlerRef.current.onConfirm?.(getCustomEventDetail<LxInputEventDetail>(event)),
    },
    keyboardheightchange: {
      handleEvent: (event: Event) => handlerRef.current.onKeyboardHeightChange?.(getCustomEventDetail<LxInputEventDetail>(event)),
    },
    nicknamereview: {
      handleEvent: (event: Event) => handlerRef.current.onNicknameReview?.(getCustomEventDetail<LxInputEventDetail>(event)),
    },
  });
  const elementRefCallback = useCallback((element: HTMLElement | null) => {
    boundElementRef.current = bindElementEvents(boundElementRef.current, element, listenerMapRef.current);
    elementRef.current = element;
    assignForwardedRef(ref, element);
  }, [ref]);

  useEffect(() => () => {
    unbindElementEvents(boundElementRef.current, listenerMapRef.current);
    boundElementRef.current = null;
    elementRef.current = null;
  }, []);

  useEffect(() => {
    const el = elementRef.current;
    if (!el) return;
    const setAttr = (name: string, next: string | null) => {
      if (next === null) {
        el.removeAttribute(name);
        return;
      }
      el.setAttribute(name, next);
    };

    if (type && String(type).trim().length > 0) {
      el.setAttribute("type", String(type).trim().toLowerCase());
    } else {
      el.removeAttribute("type");
    }
    if (password) {
      el.setAttribute("password", "true");
    } else {
      el.removeAttribute("password");
    }
    setAttr("value", value !== undefined ? String(value) : null);
    setAttr("focus", focus !== undefined ? (focus ? "true" : "false") : null);
    setAttr("maxlength", maxlength !== undefined ? String(maxlength) : null);
    setAttr("placeholder-style", placeholderStyle ? String(placeholderStyle) : null);
  }, [type, password, value, focus, maxlength, placeholderStyle]);

  // Set pageBindings property on custom element
  useEffect(() => {
    const el = elementRef.current as any;
    if (el && pageBindings) {
      el.pageBindings = pageBindings;
    }
  }, [pageBindings]);

  const inputProps = buildInputNativeAttrs({
    id,
    value,
    defaultValue,
    type,
    password,
    placeholder,
    placeholderStyle,
    placeholderClass,
    maxlength,
    cursorSpacing,
    autoFocus,
    disabled,
    focus,
    confirmType,
    alwaysEmbed,
    confirmHold,
    cursor,
    cursorColor,
    selectionStart,
    selectionEnd,
    adjustPosition,
    holdKeyboard,
  }, rest as Record<string, unknown>, boundElementRef.current !== null);

  return React.createElement("lx-input", {
    ref: elementRefCallback,
    className,
    style,
    ...inputProps,
  });
});

LxInput.displayName = "LxInput";
