// packages/lingxia-vue/src/LxNavigator.vue
<script setup lang="ts">
import { ref, h, onMounted, onBeforeUnmount, useAttrs } from 'vue';
import type { LxNavigatorEvent } from '@lingxia/elements';
import { buildNavigatorNativeAttrs } from '@lingxia/elements';
import type { LxNavigatorProps } from './types.js';
import '@lingxia/elements';

const props = withDefaults(defineProps<LxNavigatorProps>(), {
  openType: 'navigate',
  delta: 1,
  hoverClass: 'navigator-hover',
  hoverStopPropagation: false,
  hoverStartTime: 20,
  hoverStayTime: 70,
});

const slots = defineSlots();
const attrs = useAttrs();

const emit = defineEmits<{
  success: [e: LxNavigatorEvent];
  fail: [e: LxNavigatorEvent];
  complete: [e: LxNavigatorEvent];
}>();

const elementRef = ref<HTMLElement | null>(null);

const handleSuccess = (e: Event) => emit('success', e as LxNavigatorEvent);
const handleFail = (e: Event) => emit('fail', e as LxNavigatorEvent);
const handleComplete = (e: Event) => emit('complete', e as LxNavigatorEvent);
const successListener: EventListenerObject = { handleEvent: handleSuccess };
const failListener: EventListenerObject = { handleEvent: handleFail };
const completeListener: EventListenerObject = { handleEvent: handleComplete };

onMounted(() => {
  const el = elementRef.value;
  if (!el) return;
  el.addEventListener('success', successListener);
  el.addEventListener('fail', failListener);
  el.addEventListener('complete', completeListener);
});

onBeforeUnmount(() => {
  const el = elementRef.value;
  if (!el) return;
  el.removeEventListener('success', successListener);
  el.removeEventListener('fail', failListener);
  el.removeEventListener('complete', completeListener);
});

defineExpose({ el: elementRef });

const render = () => h(
  'lx-navigator',
  {
    ref: elementRef,
    ...buildNavigatorNativeAttrs({
      url: props.url,
      page: props.page,
      openType: props.openType,
      target: props.target,
      delta: props.delta,
      query: props.query,
      appId: props.appId,
      path: props.path,
      envVersion: props.envVersion,
      targetVersion: props.targetVersion,
      phoneNumber: props.phoneNumber,
      hoverClass: props.hoverClass,
      hoverStopPropagation: props.hoverStopPropagation,
      hoverStartTime: props.hoverStartTime,
      hoverStayTime: props.hoverStayTime,
    }, attrs as Record<string, unknown>),
    class: props.class ?? attrs.class,
    style: props.style ?? attrs.style,
  },
  slots.default?.()
);
</script>

<template>
  <render />
</template>

// packages/lingxia-react/src/LxNavigator.tsx
import React from 'react';
import type {
  LxNavigatorAttributes,
  NavigatorEnvVersion,
  LxNavigatorEvent,
  NavigatorQuery,
  NavigatorOpenType,
  NavigatorTarget
} from '@lingxia/elements';
import { buildNavigatorNativeAttrs } from '@lingxia/elements';

// Import to ensure custom element is registered
import '@lingxia/elements';

export interface LxNavigatorProps extends Omit<LxNavigatorAttributes, 'onSuccess' | 'onFail' | 'onComplete' | 'query'> {
  // Navigation
  url?: string;
  page?: string;
  openType?: NavigatorOpenType;
  target?: NavigatorTarget; // Auto-inferred if not specified
  delta?: number;
  query?: NavigatorQuery;

  // Open external lxapp
  appId?: string;
  path?: string; // Supports query string
  envVersion?: NavigatorEnvVersion;
  targetVersion?: string;

  // Phone call
  phoneNumber?: string;

  // Hover effect
  hoverClass?: string;
  hoverStopPropagation?: boolean;
  hoverStartTime?: number;
  hoverStayTime?: number;

  // Styling
  className?: string;
  style?: React.CSSProperties;

  // Events
  onSuccess?: (e: LxNavigatorEvent) => void;
  onFail?: (e: LxNavigatorEvent) => void;
  onComplete?: (e: LxNavigatorEvent) => void;

  // Children
  children?: React.ReactNode;
}

export const LxNavigator = React.forwardRef<HTMLElement, LxNavigatorProps>(
  (props, ref) => {
    const {
      url,
      page,
      openType = 'navigate',
      target, // Auto-inferred, no default
      delta = 1,
      query,
      appId,
      path,
      envVersion,
      targetVersion,
      phoneNumber,
      hoverClass = 'navigator-hover',
      hoverStopPropagation = false,
      hoverStartTime = 20,
      hoverStayTime = 70,
      className,
      style,
      onSuccess,
      onFail,
      onComplete,
      children,
      ...rest
    } = props;

    const elementRef = React.useRef<HTMLElement>(null);

    React.useImperativeHandle(ref, () => elementRef.current!);

    React.useEffect(() => {
      const element = elementRef.current;
      if (!element) return;

      const handleSuccess = (e: Event) => {
        if (onSuccess) {
          onSuccess(e as LxNavigatorEvent);
        }
      };

      const handleFail = (e: Event) => {
        if (onFail) {
          onFail(e as LxNavigatorEvent);
        }
      };

      const handleComplete = (e: Event) => {
        if (onComplete) {
          onComplete(e as LxNavigatorEvent);
        }
      };
      const successListener: EventListenerObject = { handleEvent: handleSuccess };
      const failListener: EventListenerObject = { handleEvent: handleFail };
      const completeListener: EventListenerObject = { handleEvent: handleComplete };

      element.addEventListener('success', successListener);
      element.addEventListener('fail', failListener);
      element.addEventListener('complete', completeListener);

      return () => {
        element.removeEventListener('success', successListener);
        element.removeEventListener('fail', failListener);
        element.removeEventListener('complete', completeListener);
      };
    }, [onSuccess, onFail, onComplete]);

    const navigatorProps = buildNavigatorNativeAttrs({
      url,
      page,
      openType,
      target,
      delta,
      query,
      appId,
      path,
      envVersion,
      targetVersion,
      phoneNumber,
      hoverClass,
      hoverStopPropagation,
      hoverStartTime,
      hoverStayTime,
    }, rest as Record<string, unknown>);

    return React.createElement('lx-navigator', {
      ref: elementRef,
      className,
      style,
      ...navigatorProps
    }, children);
  }
);

LxNavigator.displayName = 'LxNavigator';
