// packages/lingxia-vue/src/LxPicker.vue
<script setup lang="ts">
import { ref, computed, h, onBeforeUnmount, useAttrs, useId, watch } from 'vue';
import { registerPickerComponent } from '@lingxia/elements';
import {
  buildPickerNativeAttrs,
  getPickerDisplayText,
  getPickerValueFromIndex,
} from '@lingxia/elements';
import { bindElementEvents, getCustomEventDetail, unbindElementEvents } from './text_component_shared.js';
import type { LxPickerProps } from './types.js';

const props = withDefaults(defineProps<LxPickerProps>(), {
  placeholder: 'Please select',
  disabled: false,
});
const attrs = useAttrs();

const slots = defineSlots();

const emit = defineEmits<{
  'update:modelValue': [value: string | string[]];
  confirm: [value: string | string[]];
  cancel: [];
  scroll: [value: string | string[]];
}>();

if (typeof window !== 'undefined') {
  registerPickerComponent();
}

const visible = ref(false);
const vueId = useId();
const pickerId = computed(() => `lx-picker-${vueId.replace(/[:]/g, '')}`);
const pickerRef = ref<HTMLElement | null>(null);
let boundElement: HTMLElement | null = null;
const pickerEventListeners: Record<string, EventListenerObject> = {
  change: {
    handleEvent: (event: Event) => handleChange(event),
  },
  scroll: {
    handleEvent: (event: Event) => handleScroll(event),
  },
};

const displayText = computed(() => getPickerDisplayText(props.modelValue, props.fields));

function handleChange(e: Event) {
  props.onChange?.(e);
  const detail = getCustomEventDetail<{
    confirmed?: boolean;
    cancelled?: boolean;
    value?: string | string[];
    index?: number | number[];
  }>(e);
  if (detail.confirmed) {
    if (props.mode === 'date' || props.mode === 'time') {
      const nextValue = detail.value ?? '';
      emit('update:modelValue', nextValue);
      emit('confirm', nextValue);
    } else if (detail.index !== undefined) {
      const nextValue = getPickerValueFromIndex(props.columns, detail.index);
      emit('update:modelValue', nextValue);
      emit('confirm', nextValue);
    }
    visible.value = false;
  } else if (detail.cancelled) {
    emit('cancel');
    visible.value = false;
  }
}

function handleScroll(e: Event) {
  props.onNativeScroll?.(e);
  const detail = getCustomEventDetail<{
    value?: string | string[];
    index?: number | number[];
  }>(e);
  if (detail.value !== undefined) {
    emit('scroll', detail.value);
  } else if (detail.index !== undefined) {
    emit('scroll', getPickerValueFromIndex(props.columns, detail.index));
  }
}

function handleClick() {
  if (!props.disabled) visible.value = true;
}

watch(pickerRef, (element) => {
  boundElement = bindElementEvents(boundElement, element, pickerEventListeners);
});

onBeforeUnmount(() => {
  unbindElementEvents(boundElement, pickerEventListeners);
});

const pickerProps = computed(() => {
  return buildPickerNativeAttrs({
    id: pickerId.value,
    columns: props.columns,
    mode: props.mode,
    start: props.start,
    end: props.end,
    fields: props.fields,
    modelValue: props.modelValue,
    cancelText: props.cancelText,
    cancelTextColor: props.cancelTextColor,
    cancelButtonColor: props.cancelButtonColor,
    confirmText: props.confirmText,
    confirmTextColor: props.confirmTextColor,
    confirmButtonColor: props.confirmButtonColor,
  }, attrs as Record<string, unknown>);
});

const triggerStyle = computed(() => ({
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'space-between',
  padding: '12px 14px',
  backgroundColor: '#fff',
  border: '1px solid #e5e7eb',
  borderRadius: '8px',
  cursor: props.disabled ? 'not-allowed' : 'pointer',
  opacity: props.disabled ? 0.5 : 1,
  width: '100%',
  boxSizing: 'border-box',
}));

defineExpose({ el: pickerRef });

const renderPicker = () => visible.value ? h('lx-picker', { ref: pickerRef, ...pickerProps.value }) : null;
</script>

<template>
  <slot :open="handleClick" :disabled="props.disabled">
    <div :class="props.class ?? attrs.class" :style="[triggerStyle, props.style ?? attrs.style]" @click="handleClick">
      <span :style="{ color: modelValue ? '#111' : '#9ca3af' }">{{ displayText || placeholder }}</span>
      <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#9ca3af" stroke-width="2">
        <path d="M6 9l6 6 6-6" />
      </svg>
    </div>
  </slot>
  <renderPicker />
</template>

// packages/lingxia-react/src/LxPicker.tsx
import React, { forwardRef, useCallback, useId, useRef, useState } from 'react';
import { registerPickerComponent } from '@lingxia/elements';
import {
  buildPickerNativeAttrs,
  getPickerDisplayText,
  getPickerValueFromIndex,
} from '@lingxia/elements';
import {
  assignForwardedRef,
  bindElementEvents,
  getCustomEventDetail,
  unbindElementEvents,
} from './text_component_shared.js';

export interface LxPickerProps extends Omit<React.HTMLAttributes<HTMLElement>, 'onChange' | 'onScroll'> {
  // For selector/multiSelector/cascading mode
  columns?: string[][] | [string[], Record<string, string[]>];

  // For date/time mode
  mode?: 'date' | 'time';
  start?: string;   // Valid date range start: 'YYYY-MM-DD'
  end?: string;     // Valid date range end: 'YYYY-MM-DD'
  fields?: 'year' | 'month' | 'day' | 'range';

  // Value (type depends on mode)
  value?: string | string[];

  // Callbacks
  onConfirm?: (value: string | string[]) => void;
  onCancel?: () => void;
  onScroll?: (value: string | string[]) => void;
  onChange?: (event: CustomEvent) => void;
  onNativeScroll?: (event: CustomEvent) => void;

  // Logic bindings (CLI-generated)
  pageBindings?: Record<string, string>;

  // UI
  placeholder?: string;
  className?: string;
  style?: React.CSSProperties;
  disabled?: boolean;

  // Button customization
  cancelText?: string;
  cancelTextColor?: string;
  cancelButtonColor?: string;
  confirmText?: string;
  confirmTextColor?: string;
  confirmButtonColor?: string;

  children?: React.ReactNode;
}

if (typeof window !== "undefined") {
  registerPickerComponent();
}

export const LxPicker = forwardRef<HTMLElement, LxPickerProps>(({
  id,
  columns, mode, start, end, fields, value, onConfirm, onCancel, onScroll, placeholder = 'Please select',
  onChange, onNativeScroll, pageBindings,
  className, style, disabled, cancelText, cancelTextColor, cancelButtonColor,
  confirmText, confirmTextColor, confirmButtonColor, children,
  ...rest
}, ref) => {
  const [visible, setVisible] = useState(false);
  const reactId = useId();
  const pickerId = id ?? `lx-picker-${reactId.replace(/[:]/g, "")}`;
  const elementRef = useRef<HTMLElement | null>(null);
  const boundElementRef = useRef<HTMLElement | null>(null);
  const handlerRef = useRef({
    columns,
    mode,
    onConfirm,
    onCancel,
    onScroll,
    onChange,
    onNativeScroll,
  });
  handlerRef.current = {
    columns,
    mode,
    onConfirm,
    onCancel,
    onScroll,
    onChange,
    onNativeScroll,
  };
  const listenerMapRef = useRef<Record<string, EventListenerObject>>({
    change: {
      handleEvent: (event: Event) => {
        const detail = getCustomEventDetail<{
          confirmed?: boolean;
          cancelled?: boolean;
          value?: string | string[];
          index?: number | number[];
        }>(event);
        handlerRef.current.onChange?.(event as CustomEvent);
        if (detail.confirmed) {
          const nextValue =
            handlerRef.current.mode === 'date' || handlerRef.current.mode === 'time'
              ? (detail.value ?? '')
              : detail.index !== undefined
                ? getPickerValueFromIndex(handlerRef.current.columns, detail.index)
                : '';
          handlerRef.current.onConfirm?.(nextValue);
          setVisible(false);
          return;
        }
        if (detail.cancelled) {
          handlerRef.current.onCancel?.();
          setVisible(false);
        }
      },
    },
    scroll: {
      handleEvent: (event: Event) => {
        const detail = getCustomEventDetail<{
          value?: string | string[];
          index?: number | number[];
        }>(event);
        handlerRef.current.onNativeScroll?.(event as CustomEvent);
        if (detail.value !== undefined) {
          handlerRef.current.onScroll?.(detail.value);
          return;
        }
        if (detail.index !== undefined) {
          handlerRef.current.onScroll?.(getPickerValueFromIndex(handlerRef.current.columns, detail.index));
        }
      },
    },
  });
  const elementRefCallback = useCallback((element: HTMLElement | null) => {
    boundElementRef.current = bindElementEvents(boundElementRef.current, element, listenerMapRef.current);
    elementRef.current = element;
    assignForwardedRef(ref, element);

    // Set pageBindings on custom element
    if (element && pageBindings) {
      (element as any).pageBindings = pageBindings;
    }
  }, [ref, pageBindings]);
  React.useEffect(() => () => {
    unbindElementEvents(boundElementRef.current, listenerMapRef.current);
    boundElementRef.current = null;
    elementRef.current = null;
  }, []);

  const handleClick = () => !disabled && setVisible(true);
  const pickerProps = buildPickerNativeAttrs({
    id: pickerId,
    columns,
    mode,
    start,
    end,
    fields,
    value,
    cancelText,
    cancelTextColor,
    cancelButtonColor,
    confirmText,
    confirmTextColor,
    confirmButtonColor,
  }, rest as Record<string, unknown>);
  const displayText = getPickerDisplayText(value, fields);

  return (
    <>
      {children ? (
        <div
          onClick={handleClick}
          className={className}
          style={{
            cursor: disabled ? 'not-allowed' : 'pointer',
            opacity: disabled ? 0.5 : 1,
            ...style,
          }}
        >
          {children}
        </div>
      ) : (
        <div
          onClick={handleClick}
          className={className}
          style={{
            display: 'flex', alignItems: 'center', justifyContent: 'space-between',
            padding: '12px 14px', backgroundColor: '#fff', border: '1px solid #e5e7eb',
            borderRadius: '8px', cursor: disabled ? 'not-allowed' : 'pointer',
            opacity: disabled ? 0.5 : 1, width: '100%', boxSizing: 'border-box',
            ...style,
          }}
        >
          <span style={{ color: value ? '#111' : '#9ca3af' }}>{displayText || placeholder}</span>
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#9ca3af" strokeWidth="2">
            <path d="M6 9l6 6 6-6" />
          </svg>
        </div>
      )}
      {visible && React.createElement('lx-picker', { ref: elementRefCallback, ...pickerProps })}
    </>
  );
});

LxPicker.displayName = 'LxPicker';
