// packages/lingxia-vue/src/LxTextarea.vue
<script setup lang="ts">
import { computed, h, onBeforeUnmount, ref, useAttrs, watch } from 'vue';
import { registerTextareaComponent } from '@lingxia/elements';
import { buildTextareaNativeAttrs } from '@lingxia/elements';
import type { LxTextareaProps } from './types.js';
import {
  bindElementEvents,
  getCustomEventDetail,
  unbindElementEvents,
} from './text_component_shared.js';

const props = withDefaults(defineProps<LxTextareaProps>(), {
  disabled: false,
});
const attrs = useAttrs();

const emit = defineEmits<{
  'update:modelValue': [value: string];
  input: [detail: Record<string, unknown>];
  change: [detail: Record<string, unknown>];
  focus: [detail: Record<string, unknown>];
  blur: [detail: Record<string, unknown>];
  confirm: [detail: Record<string, unknown>];
  lineChange: [detail: Record<string, unknown>];
  keyboardHeightChange: [detail: Record<string, unknown>];
}>();

if (typeof window !== 'undefined') {
  registerTextareaComponent();
}

const elementRef = ref<HTMLElement | null>(null);
let boundElement: HTMLElement | null = null;

const textareaEventListeners: Record<string, EventListenerObject> = {
  input: {
    handleEvent: (event: Event) => {
      const detail = getCustomEventDetail<Record<string, unknown>>(event);
      if (typeof detail.value === 'string') {
        emit('update:modelValue', detail.value);
      }
      emit('input', detail);
    },
  },
  change: {
    handleEvent: (event: Event) => emit('change', getCustomEventDetail<Record<string, unknown>>(event)),
  },
  focus: {
    handleEvent: (event: Event) => emit('focus', getCustomEventDetail<Record<string, unknown>>(event)),
  },
  blur: {
    handleEvent: (event: Event) => emit('blur', getCustomEventDetail<Record<string, unknown>>(event)),
  },
  confirm: {
    handleEvent: (event: Event) => emit('confirm', getCustomEventDetail<Record<string, unknown>>(event)),
  },
  linechange: {
    handleEvent: (event: Event) => emit('lineChange', getCustomEventDetail<Record<string, unknown>>(event)),
  },
  keyboardheightchange: {
    handleEvent: (event: Event) => emit('keyboardHeightChange', getCustomEventDetail<Record<string, unknown>>(event)),
  },
};

watch(elementRef, (element) => {
  boundElement = bindElementEvents(boundElement, element, textareaEventListeners);
});

onBeforeUnmount(() => {
  unbindElementEvents(boundElement, textareaEventListeners);
});

const textareaProps = computed<Record<string, unknown>>(() => {
  const result: Record<string, unknown> = buildTextareaNativeAttrs({
    ...props,
    id: props.id ?? (typeof attrs.id === 'string' ? attrs.id : undefined),
  }, attrs as Record<string, unknown>, elementRef.value !== null);
  result.class = props.class ?? attrs.class;
  result.style = props.style ?? attrs.style;
  return result;
});

defineExpose({ el: elementRef });

const renderTextarea = () => h('lx-textarea', { ref: elementRef, ...textareaProps.value });
</script>

<template>
  <renderTextarea />
</template>

// packages/lingxia-react/src/LxTextarea.tsx
import React, { forwardRef, useCallback, useEffect, useRef } from "react";
import { registerTextareaComponent } from "@lingxia/elements";
import { buildTextareaNativeAttrs } from "@lingxia/elements";
import {
  assignForwardedRef,
  bindElementEvents,
  getCustomEventDetail,
  unbindElementEvents,
} from "./text_component_shared.js";

export interface LxTextareaEventDetail {
  value?: string;
  cursor?: number;
  lineCount?: number;
  height?: number;
  duration?: number;
  selectionStart?: number;
  selectionEnd?: number;
  heightRpx?: number;
}

export interface LxTextareaProps {
  id?: string;
  value?: string;
  defaultValue?: string;
  placeholder?: string;
  placeholderStyle?: string;
  placeholderClass?: string;
  maxlength?: number;
  disabled?: boolean;
  autoFocus?: boolean;
  focus?: boolean;
  autoHeight?: boolean;
  cursorSpacing?: number;
  showConfirmBar?: boolean;
  adjustPosition?: boolean;
  holdKeyboard?: boolean;
  disableDefaultPadding?: boolean;
  confirmType?: "send" | "search" | "next" | "go" | "done" | "return";
  confirmHold?: boolean;
  fixed?: boolean;
  adjustKeyboardTo?: "cursor" | "bottom";
  cursor?: number;
  selectionStart?: number;
  selectionEnd?: number;

  onInput?: (detail: LxTextareaEventDetail) => void;
  onChange?: (detail: LxTextareaEventDetail) => void;
  onFocus?: (detail: LxTextareaEventDetail) => void;
  onBlur?: (detail: LxTextareaEventDetail) => void;
  onConfirm?: (detail: LxTextareaEventDetail) => void;
  onLineChange?: (detail: LxTextareaEventDetail) => void;
  onKeyboardHeightChange?: (detail: LxTextareaEventDetail) => void;

  // Logic bindings (CLI-generated)
  pageBindings?: Record<string, string>;

  className?: string;
  style?: React.CSSProperties;
}

if (typeof window !== "undefined") {
  registerTextareaComponent();
}

export const LxTextarea = forwardRef<HTMLElement, LxTextareaProps>(({
  value,
  defaultValue,
  placeholder,
  placeholderStyle,
  placeholderClass,
  maxlength,
  disabled,
  autoFocus,
  focus,
  autoHeight,
  cursorSpacing,
  showConfirmBar,
  adjustPosition,
  holdKeyboard,
  disableDefaultPadding,
  confirmType,
  confirmHold,
  fixed,
  adjustKeyboardTo,
  cursor,
  selectionStart,
  selectionEnd,
  onInput,
  onChange,
  onFocus,
  onBlur,
  onConfirm,
  onLineChange,
  onKeyboardHeightChange,
  pageBindings,
  className,
  style,
  id,
  ...rest
}, ref) => {
  const elementRef = useRef<HTMLElement | null>(null);
  const boundElementRef = useRef<HTMLElement | null>(null);
  const handlerRef = useRef({
    onInput,
    onChange,
    onFocus,
    onBlur,
    onConfirm,
    onLineChange,
    onKeyboardHeightChange,
  });
  handlerRef.current = {
    onInput,
    onChange,
    onFocus,
    onBlur,
    onConfirm,
    onLineChange,
    onKeyboardHeightChange,
  };
  const listenerMapRef = useRef<Record<string, EventListenerObject>>({
    input: {
      handleEvent: (event: Event) => handlerRef.current.onInput?.(getCustomEventDetail<LxTextareaEventDetail>(event)),
    },
    change: {
      handleEvent: (event: Event) => handlerRef.current.onChange?.(getCustomEventDetail<LxTextareaEventDetail>(event)),
    },
    focus: {
      handleEvent: (event: Event) => handlerRef.current.onFocus?.(getCustomEventDetail<LxTextareaEventDetail>(event)),
    },
    blur: {
      handleEvent: (event: Event) => handlerRef.current.onBlur?.(getCustomEventDetail<LxTextareaEventDetail>(event)),
    },
    confirm: {
      handleEvent: (event: Event) => handlerRef.current.onConfirm?.(getCustomEventDetail<LxTextareaEventDetail>(event)),
    },
    linechange: {
      handleEvent: (event: Event) => handlerRef.current.onLineChange?.(getCustomEventDetail<LxTextareaEventDetail>(event)),
    },
    keyboardheightchange: {
      handleEvent: (event: Event) => handlerRef.current.onKeyboardHeightChange?.(getCustomEventDetail<LxTextareaEventDetail>(event)),
    },
  });
  const elementRefCallback = useCallback((element: HTMLElement | null) => {
    boundElementRef.current = bindElementEvents(boundElementRef.current, element, listenerMapRef.current);
    elementRef.current = element;
    assignForwardedRef(ref, element);
  }, [ref]);

  useEffect(() => () => {
    unbindElementEvents(boundElementRef.current, listenerMapRef.current);
    boundElementRef.current = null;
    elementRef.current = null;
  }, []);

  React.useEffect(() => {
    const el = elementRef.current;
    if (!el) return;
    const setAttr = (name: string, next: string | null) => {
      if (next === null) {
        el.removeAttribute(name);
        return;
      }
      el.setAttribute(name, next);
    };
    setAttr("value", value !== undefined ? String(value) : null);
    setAttr("focus", focus !== undefined ? (focus ? "true" : "false") : null);
    setAttr("maxlength", maxlength !== undefined ? String(maxlength) : null);
    setAttr("placeholder-style", placeholderStyle ? String(placeholderStyle) : null);
    setAttr("auto-height", autoHeight ? "true" : null);
  }, [value, focus, maxlength, placeholderStyle, autoHeight]);

  // Set pageBindings property on custom element
  useEffect(() => {
    const el = elementRef.current as any;
    if (el && pageBindings) {
      el.pageBindings = pageBindings;
    }
  }, [pageBindings]);

  const textareaProps = buildTextareaNativeAttrs({
    id,
    value,
    defaultValue,
    placeholder,
    placeholderStyle,
    placeholderClass,
    maxlength,
    disabled,
    autoFocus,
    focus,
    autoHeight,
    cursorSpacing,
    showConfirmBar,
    adjustPosition,
    holdKeyboard,
    disableDefaultPadding,
    confirmType,
    confirmHold,
    fixed,
    adjustKeyboardTo,
    cursor,
    selectionStart,
    selectionEnd,
  }, rest as Record<string, unknown>, boundElementRef.current !== null);

  return React.createElement("lx-textarea", {
    ref: elementRefCallback,
    className,
    style,
    ...textareaProps,
  });
});

LxTextarea.displayName = "LxTextarea";
