// packages/lingxia-react/src/LxVideo.tsx
import React, { forwardRef, useCallback, useEffect, useId, useMemo, useRef } from 'react';
import { registerVideoComponent, type LxVideoAttributes } from '@lingxia/elements';
import {
  buildVideoNativeAttrs,
  VIDEO_DOM_EVENT_MAP,
} from '@lingxia/elements';
import {
  assignForwardedRef,
  bindElementEvents,
  unbindElementEvents,
} from './text_component_shared.js';

export interface LxVideoProps
  extends LxVideoAttributes,
    Omit<
      React.HTMLAttributes<HTMLElement>,
      keyof LxVideoAttributes | "children" | "dangerouslySetInnerHTML" | "ref" | "onPlaying"
    > {}

if (typeof window !== "undefined") {
  registerVideoComponent();
}
export const LxVideo = forwardRef<HTMLElement, LxVideoProps>(({
  id,
  src,
  poster,
  objectFit,
  rotate,
  autoplay,
  loop,
  muted,
  controls,
  progressBar,
  live,
  volume,
  qualities,
  playbackRates,
  onPlayRequest,
  onPlay,
  onPlaying,
  onPause,
  onStop,
  onEnded,
  onTimeUpdate,
  onError,
  onLoadedMetadata,
  onFullscreenChange,
  onWaiting,
  onQualityChange,
  onRateChange,
  pageBindings,
  className,
  style,
  ...rest
}, ref) => {
  const elementRef = useRef<HTMLElement | null>(null);
  const boundElementRef = useRef<HTMLElement | null>(null);
  const reactId = useId();
  const resolvedId = useMemo(() => {
    if (id) return id;
    return `lx-video-${reactId.replace(/[:]/g, "")}`;
  }, [id, reactId]);
  const handlerRef = useRef({
    onPlayRequest,
    onPlay,
    onPlaying,
    onPause,
    onStop,
    onEnded,
    onTimeUpdate,
    onError,
    onLoadedMetadata,
    onFullscreenChange,
    onWaiting,
    onQualityChange,
    onRateChange,
  });
  handlerRef.current = {
    onPlayRequest,
    onPlay,
    onPlaying,
    onPause,
    onStop,
    onEnded,
    onTimeUpdate,
    onError,
    onLoadedMetadata,
    onFullscreenChange,
    onWaiting,
    onQualityChange,
    onRateChange,
  };
  const listenerMapRef = useRef<Record<string, EventListenerObject>>(
    Object.fromEntries(
      Object.entries(VIDEO_DOM_EVENT_MAP).map(([propKey, eventName]) => [
        eventName,
        {
          handleEvent: (event: Event) => {
            const handler = handlerRef.current[propKey as keyof typeof handlerRef.current];
            if (typeof handler === "function") {
              handler(event);
            }
          },
        } satisfies EventListenerObject,
      ])
    )
  );
  const elementRefCallback = useCallback((element: HTMLElement | null) => {
    boundElementRef.current = bindElementEvents(boundElementRef.current, element, listenerMapRef.current);
    elementRef.current = element;
    assignForwardedRef(ref, element);
  }, [ref]);

  useEffect(() => () => {
    unbindElementEvents(boundElementRef.current, listenerMapRef.current);
    boundElementRef.current = null;
    elementRef.current = null;
  }, []);

  useEffect(() => {
    const el = elementRef.current;
    if (!el) return;
    if (rotate === undefined || rotate === null) {
      el.removeAttribute("rotate");
    } else {
      el.setAttribute("rotate", String(rotate).trim());
    }
    if (objectFit === undefined || objectFit === null) {
      el.removeAttribute("object-fit");
    } else {
      el.setAttribute("object-fit", String(objectFit).trim().toLowerCase());
    }
  }, [rotate, objectFit]);

  // Set pageBindings property on custom element
  useEffect(() => {
    const el = elementRef.current as any;
    if (el && pageBindings) {
      el.pageBindings = pageBindings;
    }
  }, [pageBindings]);

  const domProps = buildVideoNativeAttrs({
    id: resolvedId,
    src,
    poster,
    autoplay,
    loop,
    muted,
    controls,
    progressBar,
    live,
    volume,
    qualities,
    playbackRates,
  }, rest as Record<string, unknown>);

  return React.createElement('lx-video', {
    ref: elementRefCallback,
    className,
    style,
    ...domProps
  });
});

LxVideo.displayName = 'LxVideo';

// lingxia-components/src/vue/LxVideo.vue
<script setup lang="ts">
import { ref, computed, h, onBeforeUnmount, useAttrs, useId, watch } from 'vue';
import { registerVideoComponent } from '../video.js';
import {
  buildVideoNativeAttrs,
  VIDEO_DOM_EVENT_MAP,
} from '../native_component_wrapper_shared.js';
import { bindElementEvents, unbindElementEvents } from './text_component_shared.js';
import type { LxVideoProps } from './types.js';

const props = withDefaults(defineProps<LxVideoProps>(), {
  autoplay: false,
  loop: false,
  muted: false,
  controls: true,
  progressBar: true,
  live: false,
});
const attrs = useAttrs();

const emit = defineEmits<{
  playRequest: [e: Event];
  play: [e: Event];
  playing: [e: Event];
  pause: [e: Event];
  stop: [e: Event];
  ended: [e: Event];
  timeUpdate: [e: Event];
  error: [e: Event];
  loadedMetadata: [e: Event];
  fullscreenChange: [e: Event];
  waiting: [e: Event];
  qualityChange: [e: Event];
  rateChange: [e: Event];
}>();

if (typeof window !== 'undefined') {
  registerVideoComponent();
}

const elementRef = ref<HTMLElement | null>(null);
const vueId = useId();
let boundElement: HTMLElement | null = null;

const resolvedId = computed(() => props.id || `lx-video-${vueId.replace(/[:]/g, '')}`);

const videoEventListeners: Record<string, EventListenerObject> = {
  [VIDEO_DOM_EVENT_MAP.onPlayRequest]: { handleEvent: (event: Event) => emit('playRequest', event) },
  [VIDEO_DOM_EVENT_MAP.onPlay]: { handleEvent: (event: Event) => emit('play', event) },
  [VIDEO_DOM_EVENT_MAP.onPlaying]: { handleEvent: (event: Event) => emit('playing', event) },
  [VIDEO_DOM_EVENT_MAP.onPause]: { handleEvent: (event: Event) => emit('pause', event) },
  [VIDEO_DOM_EVENT_MAP.onStop]: { handleEvent: (event: Event) => emit('stop', event) },
  [VIDEO_DOM_EVENT_MAP.onEnded]: { handleEvent: (event: Event) => emit('ended', event) },
  [VIDEO_DOM_EVENT_MAP.onTimeUpdate]: { handleEvent: (event: Event) => emit('timeUpdate', event) },
  [VIDEO_DOM_EVENT_MAP.onError]: { handleEvent: (event: Event) => emit('error', event) },
  [VIDEO_DOM_EVENT_MAP.onLoadedMetadata]: { handleEvent: (event: Event) => emit('loadedMetadata', event) },
  [VIDEO_DOM_EVENT_MAP.onFullscreenChange]: { handleEvent: (event: Event) => emit('fullscreenChange', event) },
  [VIDEO_DOM_EVENT_MAP.onWaiting]: { handleEvent: (event: Event) => emit('waiting', event) },
  [VIDEO_DOM_EVENT_MAP.onQualityChange]: { handleEvent: (event: Event) => emit('qualityChange', event) },
  [VIDEO_DOM_EVENT_MAP.onRateChange]: { handleEvent: (event: Event) => emit('rateChange', event) },
};

watch(elementRef, (element) => {
  boundElement = bindElementEvents(boundElement, element, videoEventListeners);
});

onBeforeUnmount(() => {
  unbindElementEvents(boundElement, videoEventListeners);
});

watch(
  [elementRef, () => props.rotate, () => props.objectFit],
  () => {
    const el = elementRef.value;
    if (!el) return;
    const rotate = props.rotate;
    if (rotate === undefined || rotate === null || rotate === '') {
      el.removeAttribute('rotate');
    } else {
      el.setAttribute('rotate', String(rotate).trim());
    }
    const objectFit = props.objectFit;
    if (objectFit === undefined || objectFit === null || objectFit === '') {
      el.removeAttribute('object-fit');
    } else {
      el.setAttribute('object-fit', String(objectFit).trim().toLowerCase());
    }
  },
  { immediate: true }
);

const domProps = computed(() => {
  const result = buildVideoNativeAttrs({
    ...props,
    id: resolvedId.value,
  }, attrs as Record<string, unknown>);
  return {
    ...result,
    class: props.class ?? attrs.class,
    style: props.style ?? attrs.style,
  };
});

defineExpose({ el: elementRef });

const render = () => h('lx-video', { ref: elementRef, ...domProps.value });
</script>

<template>
  <render />
</template>
